@{
    # Module identity
    ModuleVersion     = '4.14.3'
    GUID              = 'f8dff693-11ac-495b-901a-290773371ef5'
    Author            = 'Matthew Levorson'
    CompanyName       = 'NRG Technology Services / NextLayerSec LLC'
    Copyright         = '(c) 2026 NRG Technology Services. All rights reserved.'
    Description       = 'Read-only Microsoft 365 security assessment framework for MSPs. Multi-framework, multi-tenant, client-ready reporting.'

    # Runtime requirements
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')

    # Root module
    RootModule        = 'NRG-Assessment.psm1'

    # All functions exported by this module.
    # IMPORTANT: this list must stay in sync with $script:ExportedFunctions in
    # NRG-Assessment.psm1. PowerShell intersects the two lists, so a function
    # missing here is silently dropped from the exported surface.
    FunctionsToExport = @(
        'Add-NRGFinding',
        'Get-NRGFindings',
        'Clear-NRGFindings',
        'Clear-NRGState',
        'Register-NRGException',
        'Get-NRGExceptions',
        'Register-NRGCoverage',
        'Get-NRGCoverage',
        'Set-NRGRawData',
        'Get-NRGRawData',
        'Connect-NRGServices',
        'Disconnect-NRGServices',
        'ConvertTo-NRGHtmlSafe',
        'ConvertTo-NRGSafeUrl',
        'Start-NRGWebServer',
        'Get-NRGControlDefinitions',
        'Get-NRGControlById',
        'Get-NRGFrameworkCitations',
        'Get-NRGFrameworkDefinitions',
        'Get-NRGFindingRiskCost',
        'Get-NRGAggregateRisk',
        'Get-NRGRemediationRoadmap',
        'Set-NRGSensitiveFileAcl',
        'Set-NRGSensitiveFileContent',
        'Get-NRGTenantLicenseProfile',
        'Test-NRGLicenseRequirementMet',
        'Get-NRGControlLicenseStatus',
        'Get-NRGSafeProperty',
        'Get-NRGNestedProperty',
        'Test-NRGSectionCollected',
        'Test-NRGSignatureStatus',
        'Get-NRGMaturityTier',
        'Get-NRGCoverageScore',
        'Invoke-NRGCollectAADAppPermissions',
        'Test-NRGControlAppPermTenantTakeover',
        'Test-NRGControlAppPermDataAccess',
        'Get-NRGAppPermissionRiskCatalog',
        'Get-NRGAppPermissionContext',
        'Get-NRGAppPermissionTierMap',
        'Get-NRGAssessmentScope',
        'Get-NRGNISTFamilyCoverage',
        'Get-NRGNISTControlIdsFromFinding',
        'Get-NRGNISTPhysicalPosture',
        'Get-NRGNISTPhysicalDefinitions',
        'Get-NRGNISTControlCatalog',
        'Get-NRGNISTControlTitle',
        'Get-NRGNISTFamilyTitle',
        'Publish-NRGNISTMatrix',
        'Get-NRGSSPPosture',
        'Get-NRGSSPAnswers',
        'Get-NRGNIST171Catalog',
        'Get-NRGNIST171RequirementIdsFromCmmc',
        'Get-NRGOperationalImpactCatalog',
        'Get-NRGControlOperationalImpact',
        'Publish-NRGSSP',
        'Group-NRGSSPImpact',
        'Get-NRGSSPImpactLabel',
        'Get-NRGSSPQuestionnaireItems',
        'Publish-NRGSSPQuestionnaire',
        'ConvertTo-NRGSSPClientSlug',
        'ConvertTo-NRGSSPAnswerPsd1',
        'ConvertTo-NRGSSPPsd1String',
        'Get-NRGManualReviewItems',
        'Get-NRGManualReviewAnswers',
        'ConvertTo-NRGManualReviewAnswerPsd1',
        'Publish-NRGManualReviewQuestionnaire',
        'Get-NRGNISTImprovementPlan',
        'Publish-NRGImprovementPlan',
        'Publish-NRGDeviceGuide',
        'Publish-NRGDeviceBaseline',
        'Invoke-NRGCollectDeviceCompliance',
        'Test-NRGControlDevice',
        'Get-NRGDeviceControlDefinitions',
        'Get-NRGDeviceFrameworkIds',
        'Get-NRGObjectField',
        'Test-NRGDnsLookupSucceeded',
        'Get-NRGRecipientClass',
        'Invoke-NRGGraphRequest',
        'Invoke-NRGEvaluatorSafe',
        'Resolve-NRGDns',
        'Resolve-NRGTenantId',
        'Set-NRGThirdPartyEdr',
        'Set-NRGLicenseGating',
        'Get-NRGBaselineDefinition',
        'Get-NRGBaselineRequiredControls',
        'ConvertTo-NRGBaselineClientSlug',
        'Get-NRGBaselineExceptions',
        'Get-NRGBaselineCompliance',
        'Get-NRGBaselineRegressions',
        'Get-NRGBaselinePlan',
        'Compare-NRGBaselinePlan',
        'Format-NRGBaselinePlanSummary',
        'Get-NRGWorkloadSkipMap',
        'Get-NRGOptionalCollectorCatalog',
        'Get-NRGClientCollectorFlags',
        'Get-NRGBaselineReasonCodes',
        'Resolve-NRGBaselineReason',
        'ConvertTo-NRGBaselineReasonCode',
        'Get-NRGReasonSentence',
        'Get-NRGBaselineCoverage',
        'Get-NRGBaselineExceptionPath',
        'Get-NRGBaselineException',
        'New-NRGBaselineException',
        'Set-NRGBaselineException',
        'Remove-NRGBaselineException',
        'Get-NRGModuleHealth',
        'Repair-NRGModuleHealth',
        'Test-NRGModuleBundle',
        'Enable-NRGModuleBundle',
        'Disable-NRGModuleBundle',
        'New-NRGModuleBundle',
        'Get-NRGModuleInstallScope',
        'Get-NRGExoModuleFloor',
        'Get-NRGConnectErrorText',
        'Get-NRGExoConnectHint',
        'Get-NRGControlAutomationAudit',
        'Invoke-NRGCollectAADAuthPolicies',
        'Invoke-NRGCollectAADCAPolicies',
        'Invoke-NRGCollectAADUsers',
        'Invoke-NRGCollectAADRoles',
        'Invoke-NRGCollectAADPIM',
        'Invoke-NRGCollectAADIdentityGovernance',
        'Invoke-NRGCollectAADInventory',
        'Invoke-NRGCollectEXOMailboxConfig',
        'Invoke-NRGCollectEXOConnectionFilter',
        'Invoke-NRGCollectEXOInventory',
        'Invoke-NRGCollectDefender',
        'Invoke-NRGCollectDNSEmailRecords',
        'Invoke-NRGCollectSharePoint',
        'Invoke-NRGCollectTeams',
        'Invoke-NRGCollectPurview',
        'Invoke-NRGCollectIntuneEndpointSecurity',
        'Invoke-NRGCollectIntuneDeviceCompliance',
        'Invoke-NRGCollectIntuneAppProtection',
        'Invoke-NRGCollectPowerPlatform',
        'Invoke-NRGCollectM365Copilot',
        'Test-NRGControlAADLegacyAuth',
        'Test-NRGControlAADMFA',
        'Test-NRGControlAADPhishResistantMFA',
        'Test-NRGControlAADCA',
        'Test-NRGControlAADPrivAccess',
        'Test-NRGControlAADSignInRisk',
        'Test-NRGControlAADUserRisk',
        'Test-NRGControlAADNamedLocations',
        'Test-NRGControlAADDeviceComplianceCA',
        'Test-NRGControlAADNoPermanentAdmins',
        'Test-NRGControlAADPIMMFA',
        'Test-NRGControlAADPIMJustification',
        'Test-NRGControlAADPIMApproval',
        'Test-NRGControlAADPIMDuration',
        'Test-NRGControlAADGuestInvite',
        'Test-NRGControlAADExternalCollab',
        'Test-NRGControlAADGuestPermissions',
        'Test-NRGControlAADSSPR',
        'Test-NRGControlAADSSPRMethods',
        'Test-NRGControlAADUserAppReg',
        'Test-NRGControlAADUserConsent',
        'Test-NRGControlAADAdminConsentWorkflow',
        'Test-NRGControlAADPasswordProtection',
        'Test-NRGControlAADBreakGlass',
        'Test-NRGControlAADPIMAlerts',
        'Test-NRGControlAADAccessReviews',
        'Test-NRGControlAADAuthenticatorNumberMatch',
        'Test-NRGControlAADPasswordless',
        'Test-NRGControlAADIdentityProtection',
        'Test-NRGControlAADPrivCloudOnly',
        'Test-NRGControlAADBreakGlassMonitoring',
        'Test-NRGControlAADSignInFrequency',
        'Test-NRGControlAADDeviceCode',
        'Test-NRGControlAADNoGuestInPrivRoles',
        'Test-NRGControlAADRiskyServicePrincipals',
        'Test-NRGControlAADTokenProtection',
        'Test-NRGControlAADContinuousAccess',
        'Test-NRGControlAADCrossTenantAccess',
        'Test-NRGControlAADPrivilegedWorkstation',
        'Test-NRGControlAADTermsOfUse',
        'Test-NRGControlAADWorkloadIdentityCA',
        'Test-NRGControlDNSSPF',
        'Test-NRGControlDNSDKIM',
        'Test-NRGControlDNSDMARC',
        'Test-NRGControlDNSMTASTS',
        'Test-NRGControlDNSTLSRPT',
        'Test-NRGControlDNSDNSSEC',
        'Test-NRGControlDNSDkimRotation',
        'Test-NRGControlDNSCAA',
        'Test-NRGControlDNSTLSCertExpiry',
        'Test-NRGControlDNSCertTransparency',
        'Test-NRGControlEXOMailboxHoldCoverage',
        'Test-NRGControlEXODeletedItemRetention',
        'Test-NRGControlSPODepartedUserRetention',
        'Test-NRGControlEXOMailFlowConnectors',
        'Test-NRGControlEXOTransportRuleContents',
        'Test-NRGControlDefenderTenantAllowBlockList',
        'Test-NRGControlAADAppCredentialExpiry',
        'Get-NRGAcceptedDomainSet',
        'Test-NRGRecipientIsExternal',
        'Test-NRGControlEXOMailboxAudit',
        'Test-NRGControlEXOSmtpAuth',
        'Test-NRGControlEXOAutoForward',
        'Test-NRGControlEXODKIM',
        'Test-NRGControlEXOAntiPhish',
        'Test-NRGControlEXOModernAuth',
        'Test-NRGControlEXOHonorDMARC',
        'Test-NRGControlEXOPop3',
        'Test-NRGControlEXOImap',
        'Test-NRGControlEXOCustomerLockbox',
        'Test-NRGControlEXOSharedMailbox',
        'Test-NRGControlEXOConnectionFilter',
        'Test-NRGControlEXOOutboundLimits',
        'Test-NRGControlEXOAlertForwarding',
        'Test-NRGControlEXOAlertVolume',
        'Test-NRGControlEXOTransportAudit',
        'Test-NRGControlEXOAuditAgeLimit',
        'Test-NRGControlEXOAdminAudit',
        'Test-NRGControlEXOSafeAttachmentsSPO',
        'Test-NRGControlEXOAntiSpamInbound',
        'Test-NRGControlEXOPerUserAudit',
        'Test-NRGControlEXOPriorityAccountProtection',
        'Test-NRGControlEXOSafeSenderOverride',
        'Test-NRGControlEXOMailboxForwarding',
        'Test-NRGControlEXOInboxRulesForwarding',
        'Test-NRGControlEXOAuditDisabledMailboxes',
        'Test-NRGControlEXOSmtpAuthExceptions',
        'Test-NRGControlDefender',
        'Test-NRGControlDefenderPresetPolicies',
        'Test-NRGControlDefenderZAP',
        'Test-NRGControlDefenderCommonAttachments',
        'Test-NRGControlDefenderQuarantine',
        'Test-NRGControlDefenderHCSpam',
        'Test-NRGControlDefenderBulkThreshold',
        'Test-NRGControlDefenderUnauthSender',
        'Test-NRGControlDefenderViaTag',
        'Test-NRGControlDefenderMDCA',
        'Test-NRGControlDefenderAlertNotification',
        'Test-NRGControlDefenderDLPWorkloads',
        'Test-NRGControlDefenderDLPSITs',
        'Test-NRGControlDefenderRiskyAppAlerts',
        'Test-NRGControlDefenderPriorityAccounts',
        'Test-NRGControlDefenderEndpointDLP',
        'Test-NRGControlDefenderAttackSim',
        'Test-NRGControlDefenderSafeLinksOffice',
        'Test-NRGControlSharePoint',
        'Test-NRGControlSPOOneDriveSync',
        'Test-NRGControlSPOLinkExpiration',
        'Test-NRGControlSPOAppsFromStore',
        'Test-NRGControlSPOCustomScript',
        'Test-NRGControlSPO3PStorage',
        'Test-NRGControlSPOEmailAttestation',
        'Test-NRGControlSPOReauth',
        'Test-NRGControlSPODomainSync',
        'Test-NRGControlSPOSiteAdmins',
        'Test-NRGControlSPOSharingNotifications',
        'Test-NRGControlSPOVersionHistory',
        'Test-NRGControlSPOGuestExpiry',
        'Test-NRGControlTeams',
        'Test-NRGControlTeamsSkype',
        'Test-NRGControlTeamsUnverifiedApps',
        'Test-NRGControlTeams3PStorage',
        'Test-NRGControlTeamsEmailIntegration',
        'Test-NRGControlTeamsRecordingExternal',
        'Test-NRGControlTeamsBroadChannel',
        'Test-NRGControlTeamsExternalChat',
        'Test-NRGControlTeamsPSTN',
        'Test-NRGControlTeamsWatermarks',
        'Test-NRGControlTeamsAutoAdmit',
        'Test-NRGControlTeamsMeetingChat',
        'Test-NRGControlTeamsChatCopy',
        'Test-NRGControlTeamsMeetingRecordingScope',
        'Test-NRGControlTeamsAnonymousStart',
        'Test-NRGControlTeamsFederationAllowlist',
        'Test-NRGControlTeamsLiveEvents',
        'Test-NRGControlTeamsRecordingRetention',
        'Test-NRGControlPurview',
        'Test-NRGControlPurviewAuditSearch',
        'Test-NRGControlPurviewCommCompliance',
        'Test-NRGControlPurviewInfoBarriers',
        'Test-NRGControlPurviewInsiderRisk',
        'Test-NRGControlPurviewRetention',
        'Test-NRGControlPurviewAutoLabel',
        'Test-NRGControlPurviewSIEMExport',
        'Test-NRGControlPurviewEDiscovery',
        'Test-NRGControlPurviewComplianceScore',
        'Test-NRGControlPurviewSensitiveInfoTypes',
        'Test-NRGControlPurviewAuditPremium',
        'Test-NRGControlPurviewAuditRetention',
        'Test-NRGControlPurviewLabelsPublished',
        'Test-NRGControlPurviewRecordsManagement',
        'Test-NRGControlIntune',
        'Test-NRGControlIntuneEDR',
        'Test-NRGControlIntuneASR',
        'Test-NRGControlIntuneFirewall',
        'Test-NRGControlIntuneMacEncryption',
        'Test-NRGControlIntuneWindowsUpdate',
        'Test-NRGControlIntuneEnrollmentRestrictions',
        'Test-NRGControlIntuneAppConfig',
        'Test-NRGControlIntuneConditionalLaunch',
        'Test-NRGControlIntuneWindowsLAPS',
        'Test-NRGControlIntuneWindowsHello',
        'Test-NRGControlIntuneUpdateCompliance',
        'Test-NRGControlIntuneMobilePIN',
        'Test-NRGControlPowerPlatform',
        'Test-NRGControlPPLConnectorClassification',
        'Test-NRGControlPPLAutomate',
        'Test-NRGControlPPLPowerApps',
        'Test-NRGControlInventoryMFAUsers',
        'Test-NRGControlInventoryStaleGuests',
        'Test-NRGControlInventoryStaleMembers',
        'Test-NRGControlInventoryOAuthApps',
        'Test-NRGControlInventoryExternalForwarding',
        'Test-NRGControlInventorySharedMailboxSignIn',
        'Test-NRGControlInventoryMailboxAuditDisabled',
        'Test-NRGControlInventorySMTPAuthUsers',
        'Test-NRGControlInventorySecureScore',
        'Test-NRGControlAICopilotSensitivityLabels',
        'Test-NRGControlAICopilotDLP',
        'Test-NRGControlAICopilotLicensedOnly',
        'Test-NRGControlAICopilotStudio',
        'Test-NRGControlAICopilotInteractionData',
        'Publish-NRGAssessmentHTML',
        'Publish-NRGAssessmentSummary',
        'Publish-NRGRemediationPlaybook',
        'Publish-NRGRemediationScript',
        'Publish-NRGComplianceMatrix',
        'Publish-NRGDeltaReport',
        'Publish-NRGMonthlyReport',
        'Connect-NRGEmailServices',
        'Disconnect-NRGEmailServices',
        'Invoke-NRGEmailCollectMailbox',
        'Get-NRGEmailDomainFromAddress',
        'Test-NRGEmailIsLegitMSDomain',
        'Test-NRGEmailMatchesMSImpersonation',
        'Test-NRGEmailControlInboxRules',
        'Test-NRGEmailControlForwarding',
        'Test-NRGEmailControlOutboundActivity',
        'Test-NRGEmailControlPhishOrigin',
        'Test-NRGEmailControlThreatIntel',
        'Publish-NRGEmailIncidentReport',
        'Connect-NRGEmailAdminServices',
        'Disconnect-NRGEmailAdminServices',
        'Invoke-NRGEmailCollectSignIns',
        'Clear-NRGSignInTriageState',
        'Test-NRGSignInControlFailedToSuccess',
        'Test-NRGSignInControlAnonymousIp',
        'Test-NRGSignInControlImpossibleTravel',
        'Test-NRGSignInControlRiskyUsers',
        'Test-NRGSignInControlGeoAnomaly',
        'Test-NRGSignInControlRankUsers',
        'Test-NRGSignInControlIPIntel',
        'Publish-NRGSignInTriageReport',
        'Get-NRGIPSignInIntel',
        'Invoke-NRGEmailCollectUserSecurity',
        'Test-NRGEmailControlOAuthConsents',
        'Test-NRGEmailControlAuthMethods'
    )

    VariablesToExport = @('NRGAssessmentVersion', 'NRGBrand')
    CmdletsToExport   = @()
    AliasesToExport   = @()

    # Required modules — must be present before this module loads.
    # Audit fix (v4.6.x LOW): MicrosoftTeams added because Connect-NRGServices
    # imports it at runtime (Teams collector wraps Get-CsTenant / Get-CsTeams*),
    # and ExchangeOnlineManagement has the same 3.7.2 floor that
    # Install-NRGPrerequisites enforces (3.7.2 added -DisableWAM, the supported
    # way around the WAM broker crash the old 3.2.0 pin worked around).
    # RequiredModules is intentionally minimal. Graph + EXO are mandatory for
    # any assessment to function. MicrosoftTeams used to be listed here but
    # was demoted to a soft dependency: Connect-NRGServices imports it
    # on-demand inside the Teams collector and skips Teams gracefully if not
    # installed. Listing it here as a hard requirement blocked the entire
    # module from loading on operator workstations that hadn't installed
    # Teams yet — the wrong failure mode for an optional collector.
    # See: v4.6.6 hotfix.
    #
    # MaximumVersion caps (ScubaGear RequiredVersions.ps1 pattern): both SDKs
    # have shipped behavior changes inside a major that broke this tool —
    # Invoke-MgGraphRequest's default output shape flipped to PSCustomObject
    # (the StrictMode nextLink crash), and an EXO module bump caused an MSAL
    # assembly manifest conflict. A cap makes adopting the next major a
    # deliberate, tested edit instead of a surprise on the operator's next
    # Update-Module.
    RequiredModules = @(
        @{ ModuleName = 'Microsoft.Graph.Authentication'; ModuleVersion = '2.20.0'; MaximumVersion = '2.99.99' },
        @{ ModuleName = 'ExchangeOnlineManagement';       ModuleVersion = '3.7.2';  MaximumVersion = '3.99.99' }
    )

    # Module metadata
    PrivateData = @{
        PSData = @{
            Tags         = @('M365', 'Security', 'Assessment', 'MSP', 'CIS', 'SCuBA', 'NIST', 'CMMC')
            ProjectUri   = 'https://github.com/Blackvectra/NRG-Assessment-Tool'
            LicenseUri   = 'https://github.com/Blackvectra/NRG-Assessment-Tool/blob/main/LICENSE'
            ReleaseNotes = @'
See CHANGELOG.md in the repository root for the current release's notes.
https://github.com/Blackvectra/NRG-Assessment-Tool/blob/main/CHANGELOG.md
'@
        }
    }
}
