@{
    # Module identity
    ModuleVersion     = '4.14.3'
    GUID              = 'f8dff693-11ac-495b-901a-290773371ef5'
    Author            = 'Matthew Levorson'
    CompanyName       = 'TenantPosture'
    Copyright         = '(c) 2026 NRG Technology Services. All rights reserved.'
    Description       = 'Read-only Microsoft 365 security assessment framework for MSPs. Multi-framework, multi-tenant, client-ready reporting.'

    # Runtime requirements
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')

    # Root module
    RootModule        = 'TenantPosture.psm1'

    # All functions exported by this module.
    # IMPORTANT: this list must stay in sync with $script:ExportedFunctions in
    # TenantPosture.psm1. PowerShell intersects the two lists, so a function
    # missing here is silently dropped from the exported surface.
    FunctionsToExport = @(
        'Add-TPFinding',
        'Get-TPFindings',
        'Clear-TPFindings',
        'Clear-TPState',
        'Register-TPException',
        'Get-TPExceptions',
        'Register-TPCoverage',
        'Get-TPCoverage',
        'Set-TPRawData',
        'Get-TPRawData',
        'Connect-TPServices',
        'Disconnect-TPServices',
        'ConvertTo-TPHtmlSafe',
        'ConvertTo-TPSafeUrl',
        'Start-TPWebServer',
        'Get-TPControlDefinitions',
        'Get-TPControlById',
        'Get-TPFrameworkCitations',
        'Get-TPFrameworkDefinitions',
        'Get-TPFindingRiskCost',
        'Get-TPAggregateRisk',
        'Get-TPRemediationRoadmap',
        'Set-TPSensitiveFileAcl',
        'Set-TPSensitiveFileContent',
        'Get-TPTenantLicenseProfile',
        'Test-TPLicenseRequirementMet',
        'Get-TPControlLicenseStatus',
        'Get-TPSafeProperty',
        'Get-TPNestedProperty',
        'Test-TPSectionCollected',
        'Test-TPSignatureStatus',
        'Get-TPMaturityTier',
        'Get-TPCoverageScore',
        'Invoke-TPCollectAADAppPermissions',
        'Test-TPControlAppPermTenantTakeover',
        'Test-TPControlAppPermDataAccess',
        'Get-TPAppPermissionRiskCatalog',
        'Get-TPAppPermissionContext',
        'Get-TPAppPermissionTierMap',
        'Get-TPAssessmentScope',
        'Get-TPNISTFamilyCoverage',
        'Get-TPNISTControlIdsFromFinding',
        'Get-TPNISTPhysicalPosture',
        'Get-TPNISTPhysicalDefinitions',
        'Get-TPNISTControlCatalog',
        'Get-TPNISTControlTitle',
        'Get-TPNISTFamilyTitle',
        'Publish-TPNISTMatrix',
        'Get-TPSSPPosture',
        'Get-TPSSPAnswers',
        'Get-TPNIST171Catalog',
        'Get-TPNIST171RequirementIdsFromCmmc',
        'Get-TPOperationalImpactCatalog',
        'Get-TPControlOperationalImpact',
        'Publish-TPSSP',
        'Group-TPSSPImpact',
        'Get-TPSSPImpactLabel',
        'Get-TPSSPQuestionnaireItems',
        'Publish-TPSSPQuestionnaire',
        'Get-TPHipaaReadiness',
        'Get-TPHipaaCatalog',
        'Get-TPHipaaCitationsFromText',
        'Publish-TPHipaaReadiness',
        'ConvertTo-TPSSPClientSlug',
        'ConvertTo-TPSSPAnswerPsd1',
        'ConvertTo-TPSSPPsd1String',
        'Get-TPManualReviewItems',
        'Get-TPManualReviewAnswers',
        'ConvertTo-TPManualReviewAnswerPsd1',
        'Publish-TPManualReviewQuestionnaire',
        'Get-TPNISTImprovementPlan',
        'Publish-TPImprovementPlan',
        'Publish-TPDeviceGuide',
        'Publish-TPDeviceBaseline',
        'Invoke-TPCollectDeviceCompliance',
        'Test-TPControlDevice',
        'Get-TPDeviceControlDefinitions',
        'Get-TPDeviceFrameworkIds',
        'Get-TPObjectField',
        'Test-TPDnsLookupSucceeded',
        'Get-TPRecipientClass',
        'Invoke-TPGraphRequest',
        'Invoke-TPEvaluatorSafe',
        'Resolve-TPDns',
        'Resolve-TPTenantId',
        'Set-TPThirdPartyEdr',
        'Set-TPThirdPartyAwareness',
        'New-TPProfile',
        'Get-TPProfile',
        'Set-TPLicenseGating',
        'Get-TPBaselineDefinition',
        'Get-TPBaselineRequiredControls',
        'ConvertTo-TPBaselineClientSlug',
        'Get-TPBaselineExceptions',
        'Get-TPBaselineCompliance',
        'Get-TPBaselineRegressions',
        'Get-TPControlStatus',
        'Get-TPAsrRuleModes',
        'Get-TPScubaAlignment',
        'Publish-TPReportSite',
        'Publish-TPActionPlan',
        'Get-TPFindingLimitKind',
        'Get-TPExclusionCoverage',
        'Get-TPCAEffectiveCoverage',
        'Get-TPCANarrowing',
        'Get-TPCACoverageVerdict',
        'Get-TPCAPrincipalExclusions',
        'Get-TPDlpRuleStates',
        'Get-TPDlpSensitiveTypeNames',
        'Get-TPDlpLocationScope',
        'Get-TPStandards',
        'Add-TPExpectedStateFinding',
        'Get-TPDmarcReportAddresses',
        'Test-TPDmarcReportAddress',
        'Get-TPAvSettings',
        'Test-TPAvSettingSet',
        'Get-TPAsrRequiredRules',
        'Test-TPAsrRuleSet',
        'Set-TPMonitoringAddresses',
        'Get-TPMonitoringAddresses',
        'Get-TPAlertRouting',
        'Get-TPBaselinePlan',
        'Compare-TPBaselinePlan',
        'Format-TPBaselinePlanSummary',
        'Get-TPWorkloadSkipMap',
        'Get-TPOptionalCollectorCatalog',
        'Get-TPClientCollectorFlags',
        'Get-TPBaselineReasonCodes',
        'Resolve-TPBaselineReason',
        'ConvertTo-TPBaselineReasonCode',
        'Get-TPReasonSentence',
        'Get-TPBaselineCoverage',
        'Get-TPBaselineExceptionPath',
        'Get-TPBaselineException',
        'New-TPBaselineException',
        'Set-TPBaselineException',
        'Remove-TPBaselineException',
        'Get-TPModuleHealth',
        'Repair-TPModuleHealth',
        'Get-TPModuleInstallScope',
        'Get-TPExoModuleFloor',
        'Get-TPConnectErrorText',
        'Get-TPExoConnectHint',
        'Get-TPCloudFileHint',
        'Get-TPMsalConflictHint',
        'Get-TPGapSummary',
        'Format-TPGapSummary',
        'Get-TPControlViewMap',
        'Get-TPEvidenceLimitMap',
        'Get-TPEvidenceLimitNote',
        'Get-TPEvidenceLimitMd',
        'Test-TPSafeModuleVersionPath',
        'Get-TPControlAutomationAudit',
        'Invoke-TPCollectAADAuthPolicies',
        'Invoke-TPCollectAADCAPolicies',
        'Invoke-TPCollectAADUsers',
        'Invoke-TPCollectAADRoles',
        'Invoke-TPCollectAADPIM',
        'Invoke-TPCollectAADIdentityGovernance',
        'Invoke-TPCollectAADInventory',
        'Invoke-TPCollectEXOMailboxConfig',
        'Invoke-TPCollectEXOConnectionFilter',
        'Invoke-TPCollectEXOInventory',
        'Invoke-TPCollectDefender',
        'Invoke-TPCollectDNSEmailRecords',
        'Invoke-TPCollectSharePoint',
        'Invoke-TPCollectTeams',
        'Invoke-TPCollectPurview',
        'Invoke-TPCollectIntuneEndpointSecurity',
        'Invoke-TPCollectIntuneDeviceCompliance',
        'Invoke-TPCollectIntuneAppProtection',
        'Invoke-TPCollectPowerPlatform',
        'Invoke-TPCollectM365Copilot',
        'Test-TPControlAADLegacyAuth',
        'Test-TPControlAADMFA',
        'Test-TPControlAADPhishResistantMFA',
        'Test-TPControlAADCA',
        'Test-TPControlAADPrivAccess',
        'Test-TPControlAADSignInRisk',
        'Test-TPControlAADUserRisk',
        'Test-TPControlAADNamedLocations',
        'Test-TPControlAADDeviceComplianceCA',
        'Test-TPControlAADNoPermanentAdmins',
        'Test-TPControlAADPIMMFA',
        'Test-TPControlAADPIMJustification',
        'Test-TPControlAADPIMApproval',
        'Test-TPControlAADPIMDuration',
        'Test-TPControlAADGuestInvite',
        'Test-TPControlAADExternalCollab',
        'Test-TPControlAADGuestPermissions',
        'Test-TPControlAADSSPR',
        'Test-TPControlAADSSPRMethods',
        'Test-TPControlAADUserAppReg',
        'Test-TPControlAADUserConsent',
        'Test-TPControlAADAdminConsentWorkflow',
        'Test-TPControlAADPasswordProtection',
        'Test-TPControlAADBreakGlass',
        'Test-TPControlAADPIMAlerts',
        'Test-TPControlAADAccessReviews',
        'Test-TPControlAADAuthenticatorNumberMatch',
        'Test-TPControlAADPasswordless',
        'Test-TPControlAADIdentityProtection',
        'Test-TPControlAADPrivCloudOnly',
        'Test-TPControlAADBreakGlassMonitoring',
        'Test-TPControlAADSignInFrequency',
        'Test-TPControlAADDeviceCode',
        'Test-TPControlAADNoGuestInPrivRoles',
        'Test-TPControlAADRiskyServicePrincipals',
        'Test-TPControlAADTokenProtection',
        'Test-TPControlAADContinuousAccess',
        'Test-TPControlAADCrossTenantAccess',
        'Test-TPControlAADPrivilegedWorkstation',
        'Test-TPControlAADTermsOfUse',
        'Test-TPControlAADWorkloadIdentityCA',
        'Test-TPControlDNSSPF',
        'Test-TPControlDNSDKIM',
        'Test-TPControlDNSDMARC',
        'Test-TPControlDNSMTASTS',
        'Test-TPControlDNSTLSRPT',
        'Test-TPControlDNSDNSSEC',
        'Test-TPControlDNSDkimRotation',
        'Test-TPControlDNSCAA',
        'Test-TPControlDNSTLSCertExpiry',
        'Test-TPControlDNSCertTransparency',
        'Test-TPControlEXOMailboxHoldCoverage',
        'Test-TPControlEXODeletedItemRetention',
        'Test-TPControlSPODepartedUserRetention',
        'Test-TPControlEXOMailFlowConnectors',
        'Test-TPControlEXOTransportRuleContents',
        'Test-TPControlDefenderTenantAllowBlockList',
        'Test-TPControlAADAppCredentialExpiry',
        'Get-TPAcceptedDomainSet',
        'Test-TPRecipientIsExternal',
        'Test-TPControlEXOMailboxAudit',
        'Test-TPControlEXOSmtpAuth',
        'Test-TPControlEXOAutoForward',
        'Test-TPControlEXODKIM',
        'Test-TPControlEXOAntiPhish',
        'Test-TPControlEXOModernAuth',
        'Test-TPControlEXOHonorDMARC',
        'Test-TPControlEXOPop3',
        'Test-TPControlEXOImap',
        'Test-TPControlEXOCustomerLockbox',
        'Test-TPControlEXOSharedMailbox',
        'Test-TPControlEXOConnectionFilter',
        'Test-TPControlEXOOutboundLimits',
        'Test-TPControlEXOAlertForwarding',
        'Test-TPControlEXOAlertVolume',
        'Test-TPControlEXOTransportAudit',
        'Test-TPControlEXOAuditAgeLimit',
        'Test-TPControlEXOAdminAudit',
        'Test-TPControlEXOSafeAttachmentsSPO',
        'Test-TPControlEXOAntiSpamInbound',
        'Test-TPControlEXOPerUserAudit',
        'Test-TPControlEXOPriorityAccountProtection',
        'Test-TPControlEXOSafeSenderOverride',
        'Test-TPControlEXOMailboxForwarding',
        'Test-TPControlEXOInboxRulesForwarding',
        'Test-TPControlEXOAuditDisabledMailboxes',
        'Test-TPControlEXOSmtpAuthExceptions',
        'Test-TPControlDefender',
        'Test-TPControlDefenderPresetPolicies',
        'Test-TPControlDefenderZAP',
        'Test-TPControlDefenderCommonAttachments',
        'Test-TPControlDefenderQuarantine',
        'Test-TPControlDefenderHCSpam',
        'Test-TPControlDefenderBulkThreshold',
        'Test-TPControlDefenderUnauthSender',
        'Test-TPControlDefenderViaTag',
        'Test-TPControlDefenderMDCA',
        'Test-TPControlDefenderAlertNotification',
        'Test-TPControlDefenderDLPWorkloads',
        'Test-TPControlDefenderDLPSITs',
        'Test-TPControlDefenderRiskyAppAlerts',
        'Test-TPControlDefenderPriorityAccounts',
        'Test-TPControlDefenderEndpointDLP',
        'Test-TPControlDefenderAttackSim',
        'Test-TPControlDefenderSafeLinksOffice',
        'Test-TPControlSharePoint',
        'Test-TPControlSPOOneDriveSync',
        'Test-TPControlSPOLinkExpiration',
        'Test-TPControlSPOAppsFromStore',
        'Test-TPControlSPOCustomScript',
        'Test-TPControlSPO3PStorage',
        'Test-TPControlSPOEmailAttestation',
        'Test-TPControlSPOReauth',
        'Test-TPControlSPODomainSync',
        'Test-TPControlSPOSiteAdmins',
        'Test-TPControlSPOSharingNotifications',
        'Test-TPControlSPOVersionHistory',
        'Test-TPControlSPOGuestExpiry',
        'Test-TPControlTeams',
        'Test-TPControlTeamsSkype',
        'Test-TPControlTeamsUnverifiedApps',
        'Test-TPControlTeams3PStorage',
        'Test-TPControlTeamsEmailIntegration',
        'Test-TPControlTeamsRecordingExternal',
        'Test-TPControlTeamsBroadChannel',
        'Test-TPControlTeamsExternalChat',
        'Test-TPControlTeamsPSTN',
        'Test-TPControlTeamsWatermarks',
        'Test-TPControlTeamsAutoAdmit',
        'Test-TPControlTeamsMeetingChat',
        'Test-TPControlTeamsChatCopy',
        'Test-TPControlTeamsMeetingRecordingScope',
        'Test-TPControlTeamsAnonymousStart',
        'Test-TPControlTeamsFederationAllowlist',
        'Test-TPControlTeamsLiveEvents',
        'Test-TPControlTeamsRecordingRetention',
        'Test-TPControlPurview',
        'Test-TPControlPurviewAuditSearch',
        'Test-TPControlPurviewCommCompliance',
        'Test-TPControlPurviewInfoBarriers',
        'Test-TPControlPurviewInsiderRisk',
        'Test-TPControlPurviewRetention',
        'Test-TPControlPurviewAutoLabel',
        'Test-TPControlPurviewSIEMExport',
        'Test-TPControlPurviewEDiscovery',
        'Test-TPControlPurviewComplianceScore',
        'Test-TPControlPurviewSensitiveInfoTypes',
        'Test-TPControlPurviewAuditPremium',
        'Test-TPControlPurviewAuditRetention',
        'Test-TPControlPurviewLabelsPublished',
        'Test-TPControlPurviewRecordsManagement',
        'Test-TPControlIntune',
        'Test-TPControlIntuneEDR',
        'Test-TPControlIntuneASR',
        'Test-TPControlIntuneFirewall',
        'Test-TPControlIntuneMacEncryption',
        'Test-TPControlIntuneWindowsUpdate',
        'Test-TPControlIntuneEnrollmentRestrictions',
        'Test-TPControlIntuneAppConfig',
        'Test-TPControlIntuneConditionalLaunch',
        'Test-TPControlIntuneWindowsLAPS',
        'Test-TPControlIntuneWindowsHello',
        'Test-TPControlIntuneUpdateCompliance',
        'Test-TPControlIntuneMobilePIN',
        'Test-TPControlPowerPlatform',
        'Test-TPControlPPLConnectorClassification',
        'Test-TPControlPPLAutomate',
        'Test-TPControlPPLPowerApps',
        'Test-TPControlInventoryMFAUsers',
        'Test-TPControlInventoryStaleGuests',
        'Test-TPControlInventoryStaleMembers',
        'Test-TPControlInventoryOAuthApps',
        'Test-TPControlInventoryExternalForwarding',
        'Test-TPControlInventorySharedMailboxSignIn',
        'Test-TPControlInventoryMailboxAuditDisabled',
        'Test-TPControlInventorySMTPAuthUsers',
        'Test-TPControlInventorySecureScore',
        'Test-TPControlAICopilotSensitivityLabels',
        'Test-TPControlAICopilotDLP',
        'Test-TPControlAICopilotLicensedOnly',
        'Test-TPControlAICopilotStudio',
        'Test-TPControlAICopilotInteractionData',
        'Publish-TPAssessmentHTML',
        'Publish-TPAssessmentSummary',
        'Publish-TPRemediationPlaybook',
        'Publish-TPRemediationScript',
        'Publish-TPComplianceMatrix',
        'Publish-TPDeltaReport',
        'Publish-TPMonthlyReport',
        'Connect-TPEmailServices',
        'Disconnect-TPEmailServices',
        'Invoke-TPEmailCollectMailbox',
        'Get-TPEmailDomainFromAddress',
        'Test-TPEmailIsLegitMSDomain',
        'Test-TPEmailMatchesMSImpersonation',
        'Test-TPEmailControlInboxRules',
        'Test-TPEmailControlForwarding',
        'Test-TPEmailControlOutboundActivity',
        'Test-TPEmailControlPhishOrigin',
        'Test-TPEmailControlThreatIntel',
        'Publish-TPEmailIncidentReport',
        'Connect-TPEmailAdminServices',
        'Disconnect-TPEmailAdminServices',
        'Invoke-TPEmailCollectSignIns',
        'Clear-TPSignInTriageState',
        'Get-TPSignInCollectionCompleteness',
        'Get-TPDeepDiveEvidenceKeys',
        'Get-TPDeepDiveEvidence',
        'Set-TPFindingSubject',
        'Test-TPSignInControlFailedToSuccess',
        'Test-TPSignInControlAnonymousIp',
        'Test-TPSignInControlImpossibleTravel',
        'Test-TPSignInControlRiskyUsers',
        'Test-TPSignInControlGeoAnomaly',
        'Test-TPSignInControlRankUsers',
        'Test-TPSignInControlIPIntel',
        'Publish-TPSignInTriageReport',
        'Get-TPIPSignInIntel',
        'Invoke-TPEmailCollectUserSecurity',
        'Test-TPEmailControlOAuthConsents',
        'Test-TPEmailControlAuthMethods'
    )

    VariablesToExport = @('TPAssessmentVersion', 'TPBrand')
    CmdletsToExport   = @()
    AliasesToExport   = @()

    # Required modules — must be present before this module loads.
    # Audit fix (v4.6.x LOW): MicrosoftTeams added because Connect-TPServices
    # imports it at runtime (Teams collector wraps Get-CsTenant / Get-CsTeams*),
    # and ExchangeOnlineManagement has the same 3.7.2 floor that
    # Install-TPPrerequisites enforces (3.7.2 added -DisableWAM, the supported
    # way around the WAM broker crash the old 3.2.0 pin worked around).
    # RequiredModules is intentionally minimal. Graph + EXO are mandatory for
    # any assessment to function. MicrosoftTeams used to be listed here but
    # was demoted to a soft dependency: Connect-TPServices imports it
    # on-demand inside the Teams collector and skips Teams gracefully if not
    # installed. Listing it here as a hard requirement blocked the entire
    # module from loading on operator workstations that hadn't installed
    # Teams yet — the wrong failure mode for an optional collector.
    # See: v4.6.6 hotfix.
    #
    # MaximumVersion caps (ScubaGear RequiredVersions.ps1 pattern): both SDKs
    # have shipped behavior changes inside a major that broke this tool —
    # Invoke-MgGraphRequest's default output shape flipped to PSCustomObject
    # (the StrictMode nextLink crash), and an EXO module bump caused an MSAL
    # assembly manifest conflict. A cap makes adopting the next major a
    # deliberate, tested edit instead of a surprise on the operator's next
    # Update-Module.
    RequiredModules = @(
        @{ ModuleName = 'Microsoft.Graph.Authentication'; ModuleVersion = '2.20.0'; MaximumVersion = '2.99.99' },
        @{ ModuleName = 'ExchangeOnlineManagement';       ModuleVersion = '3.7.2';  MaximumVersion = '3.99.99' }
    )

    # Module metadata
    PrivateData = @{
        PSData = @{
            Tags         = @('M365', 'Security', 'Assessment', 'MSP', 'CIS', 'SCuBA', 'NIST', 'CMMC')
            ProjectUri   = 'https://github.com/Blackvectra/TenantPosture'
            LicenseUri   = 'https://github.com/Blackvectra/TenantPosture/blob/main/LICENSE'
            ReleaseNotes = @'
See CHANGELOG.md in the repository root for the current release's notes.
https://github.com/Blackvectra/TenantPosture/blob/main/CHANGELOG.md
'@
        }
    }
}
