#Requires -Version 7.0
#
# Publish-NRGRemediationScript.ps1  (v4.5.5)
# Generates a tenant-specific remediation PowerShell script from Gap findings.
#
# Output: <tenant>-remediation.ps1
#   - SupportsShouldProcess — safe to run with -WhatIf first
#   - Gap findings only — no changes proposed for Satisfied/Partial
#   - Grouped by workload
#   - Each section: description, business risk, exact command, validation
#   - Header warns: review before running, test in non-prod first
#
# SECURITY: Remediation strings are sourced from controls.json which is
#   content-validated at load time. No tenant data interpolated into code.
#

function Publish-NRGRemediationScript {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [hashtable] $Metadata,
        [Parameter(Mandatory)] [object[]]  $Findings,
        [Parameter(Mandatory)] [string]    $OutputPath
    )

    $client  = $Metadata.TenantDomain ?? 'UnknownTenant'
    $date    = $Metadata.AssessmentDate ?? (Get-Date -Format 'yyyy-MM-dd')
    $version = $Metadata.ToolVersion ?? '4.5.5'
    $opUPN   = $Metadata.Operator ?? 'admin'

    # Load control definitions
    $controls = @{}
    try {
        foreach ($c in (Get-NRGControlDefinitions)) { $controls[$c.ControlId] = $c }
    } catch { }

    $sevOrder = @{ 'Critical'=0; 'High'=1; 'Medium'=2; 'Low'=3; 'Informational'=4 }
    $gaps = @($Findings | Where-Object { $_.State -eq 'Gap' }) |
            Sort-Object { $sevOrder[$_.Severity] ?? 99 }, ControlId

    $sb = [System.Text.StringBuilder]::new()

    # Header
    $null = $sb.AppendLine("#Requires -Version 7.0")
    $null = $sb.AppendLine("<#")
    $null = $sb.AppendLine(".SYNOPSIS")
    $null = $sb.AppendLine("    NRG-Assessment Remediation Script — $client")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine(".DESCRIPTION")
    $null = $sb.AppendLine("    Auto-generated remediation script for $client M365 security gaps.")
    $null = $sb.AppendLine("    Generated: $date by NRG-Assessment v$version")
    $null = $sb.AppendLine("    Operator:  $opUPN")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("    IMPORTANT: Review every command before running.")
    $null = $sb.AppendLine("    Test with -WhatIf first. Run during a maintenance window.")
    $null = $sb.AppendLine("    Some commands require specific module versions and admin roles.")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine(".PARAMETER WhatIf")
    $null = $sb.AppendLine("    Preview all changes without making them.")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine(".PARAMETER Phase")
    $null = $sb.AppendLine("    Run only a specific phase: 1 (Critical+High), 2 (Medium), 3 (Low). Default: all.")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine(".PARAMETER Workload")
    $null = $sb.AppendLine("    Run only a specific workload: AAD, EXO, DNS, DEF, SPO, TMS, INT, PVW, PPL")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine(".EXAMPLE")
    $null = $sb.AppendLine("    # Preview Phase 1 changes")
    $null = $sb.AppendLine("    .\$($client -replace '\..*$','')-remediation.ps1 -Phase 1 -WhatIf")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("    # Apply Phase 1 AAD changes only")
    $null = $sb.AppendLine("    .\$($client -replace '\..*$','')-remediation.ps1 -Phase 1 -Workload AAD")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine(".NOTES")
    $null = $sb.AppendLine("    Generated by NRG-Assessment v$version")
    $null = $sb.AppendLine("    NRG Technology Services / NextLayerSec LLC")
    $null = $sb.AppendLine("    This script is read-only until you uncomment individual remedy blocks.")
    $null = $sb.AppendLine("#>")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("[CmdletBinding(SupportsShouldProcess)]")
    $null = $sb.AppendLine("param(")
    $null = $sb.AppendLine("    [ValidateSet('1','2','3','all')]")
    $null = $sb.AppendLine("    [string] `$Phase = 'all',")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("    [ValidateSet('AAD','EXO','DNS','DEF','SPO','TMS','INT','PVW','PPL','all')]")
    $null = $sb.AppendLine("    [string] `$Workload = 'all'")
    $null = $sb.AppendLine(")")
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("Set-StrictMode -Version Latest")
    $null = $sb.AppendLine("`$ErrorActionPreference = 'Stop'")
    $null = $sb.AppendLine("")

    # Summary comment
    $null = $sb.AppendLine("# ═══════════════════════════════════════════════════════════════════")
    $null = $sb.AppendLine("# ASSESSMENT SUMMARY — $client — $date")
    $null = $sb.AppendLine("# ═══════════════════════════════════════════════════════════════════")
    $phase1Gaps = @($gaps | Where-Object { $_.Severity -in @('Critical','High') })
    $phase2Gaps = @($gaps | Where-Object { $_.Severity -eq 'Medium' })
    $phase3Gaps = @($gaps | Where-Object { $_.Severity -eq 'Low' })
    $null = $sb.AppendLine("# Total gaps:  $($gaps.Count)")
    $null = $sb.AppendLine("# Phase 1 (Critical+High): $($phase1Gaps.Count)")
    $null = $sb.AppendLine("# Phase 2 (Medium):        $($phase2Gaps.Count)")
    $null = $sb.AppendLine("# Phase 3 (Low):           $($phase3Gaps.Count)")
    $null = $sb.AppendLine("#")
    $null = $sb.AppendLine("# All remedy blocks are COMMENTED OUT by default.")
    $null = $sb.AppendLine("# Uncomment each block after reviewing it. Do not run blindly.")
    $null = $sb.AppendLine("# ═══════════════════════════════════════════════════════════════════")
    $null = $sb.AppendLine("")

    # Phase-based section header helper
    function PhaseHeader { param($n, $sev, $count)
        $lines = @()
        $lines += ""
        $lines += "# ─────────────────────────────────────────────────────────────────────"
        $lines += "# PHASE $n — $sev ($count items)"
        $lines += "# ─────────────────────────────────────────────────────────────────────"
        $lines += ""
        return $lines
    }

    function Write-GapBlock {
        param([object]$f, [hashtable]$controlDefs, [string]$phaseNum)
        $lines = @()
        $ctrl  = $controlDefs[$f.ControlId]
        $remedy = if ($ctrl -and $ctrl.Remediation) { $ctrl.Remediation } else { '# No automated remediation available — see portal guidance.' }
        $bizRisk = if ($ctrl -and $ctrl.BusinessRisk) { $ctrl.BusinessRisk } else { $f.Detail }
        $licReq  = if ($ctrl -and $ctrl.LicenseRequirement -and $ctrl.LicenseRequirement -notmatch '^Included') {
            "# REQUIRES: $($ctrl.LicenseRequirement)"
        } else { $null }

        $lines += "# ── $($f.ControlId): $($f.Title) [$($f.Severity)]"
        $lines += "# Risk: $($bizRisk -replace "`n",' ')"
        if ($f.CurrentValue) { $lines += "# Current: $($f.CurrentValue)" }
        if ($licReq) { $lines += $licReq }
        $lines += "# Phase: $phaseNum | Category: $($f.Category)"
        $lines += ""

        # Wrap actual command lines in comment — user must uncomment to run
        $lines += "if (`$Phase -in @('$phaseNum','all') -and `$Workload -in @('$($f.ControlId -replace '-\d.*$','')','all')) {"
        $lines += "    if (`$PSCmdlet.ShouldProcess('$client', '$($f.Title)')) {"

        # Break multi-line remediation into individual comment lines
        foreach ($remedyLine in ($remedy -split '\r?\n')) {
            $trimmed = $remedyLine.Trim()
            if ($trimmed -and -not $trimmed.StartsWith('#')) {
                $lines += "        # UNCOMMENT TO APPLY: $trimmed"
            } elseif ($trimmed) {
                $lines += "        $trimmed"
            }
        }

        $lines += "        Write-Host `"  [+] $($f.ControlId) — Applied`" -ForegroundColor Green"
        $lines += "    }"
        $lines += "}"
        $lines += ""
        return $lines
    }

    # Phase 1
    foreach ($line in (PhaseHeader -n 1 -sev 'CRITICAL + HIGH — Address Immediately' -count $phase1Gaps.Count)) {
        $null = $sb.AppendLine($line)
    }
    foreach ($f in $phase1Gaps) {
        foreach ($line in (Write-GapBlock -f $f -controlDefs $controls -phaseNum '1')) {
            $null = $sb.AppendLine($line)
        }
    }

    # Phase 2
    foreach ($line in (PhaseHeader -n 2 -sev 'MEDIUM — Address Within 30 Days' -count $phase2Gaps.Count)) {
        $null = $sb.AppendLine($line)
    }
    foreach ($f in $phase2Gaps) {
        foreach ($line in (Write-GapBlock -f $f -controlDefs $controls -phaseNum '2')) {
            $null = $sb.AppendLine($line)
        }
    }

    # Phase 3
    foreach ($line in (PhaseHeader -n 3 -sev 'LOW — Hardening Pass' -count $phase3Gaps.Count)) {
        $null = $sb.AppendLine($line)
    }
    foreach ($f in $phase3Gaps) {
        foreach ($line in (Write-GapBlock -f $f -controlDefs $controls -phaseNum '3')) {
            $null = $sb.AppendLine($line)
        }
    }

    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("Write-Host ''")
    $null = $sb.AppendLine("Write-Host 'Remediation script complete.' -ForegroundColor Cyan")
    $null = $sb.AppendLine("Write-Host 'Re-run NRG-Assessment to validate changes.' -ForegroundColor Cyan")

    $sb.ToString() | Out-File -LiteralPath $OutputPath -Encoding utf8
}
