#Requires -Version 7.0
#
# Publish-NRGComplianceMatrix.ps1  (v4.5.5)
# Generates a professional XLSX compliance matrix from assessment findings.
#
# Sheets:
#   1. Summary        — Overall posture, score, workload breakdown, framework scores
#   2. All Controls   — Every control with status, severity, framework citations
#   3. Gaps Only      — Filtered to Gap/Partial, with remediation commands
#   4. CIS M365 v6    — Controls mapped to CIS sections
#   5. CISA SCuBA     — Controls mapped to SCuBA policy IDs
#   6. NIST 800-53    — Controls mapped to NIST control families
#   7. CMMC 2.0       — Controls mapped to CMMC practices
#   8. ISO 27001      — Controls mapped to ISO 27001:2022 clauses
#   9. SOC 2          — Controls mapped to Trust Services Criteria
#  10. HIPAA          — Controls mapped to HIPAA §164 safeguards
#  11. NIST Physical & Device — Physical/media/maintenance 800-53 controls, with
#                        implementation options and the evidence an assessor must
#                        collect off-tenant. Unscored by design.
#  12. NIST Families  — Coverage rolled up by 800-53 control family (AC/AU/IA/...)
#  13. License Gaps   — Controls blocked by current license tier
#
# The XLSX is generated by calling an embedded Python script that uses openpyxl.
# This avoids requiring Excel or COM automation on the assessment machine.
#
# SECURITY: No tenant data is interpolated into Python code.
#           All data passes through JSON serialization → Python reads the JSON.
#

function Publish-NRGComplianceMatrix {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [hashtable] $Metadata,
        [Parameter(Mandatory)] [object[]]  $Findings,
        [Parameter(Mandatory)]
        [ValidateScript({
            if ($_ -match '\.\.[\\\/]') { throw 'Path traversal not allowed.' }
            return $true
        })]
        [string] $OutputPath
    )

    # Verify Python + openpyxl available
    $pythonCmd = $null
    foreach ($py in @('python3','python')) {
        try {
            $null = & $py -c 'import openpyxl' 2>&1
            if ($LASTEXITCODE -eq 0) { $pythonCmd = $py; break }
        } catch { }
    }
    if (-not $pythonCmd) {
        Write-Warning "openpyxl not available — skipping XLSX output. Install: pip install openpyxl"
        return
    }

    # Load control definitions for framework citations + license info
    $cdefs = @{}
    try { foreach ($c in (Get-NRGControlDefinitions)) { $cdefs[$c.ControlId] = $c } } catch { }

    # Official 800-53 Rev 5 titles for every identifier any control cites,
    # passed through the payload rather than duplicated in the embedded Python.
    # The family NAMES below are hardcoded on the Python side and that is
    # already a duplication; adding 77 control titles beside them would be a
    # second copy of Config/nist-800-53-catalog.json that rots independently of
    # the real one. Sourced here from the same catalog the standalone NIST
    # matrix uses, so the two deliverables cannot disagree about what AC-2 is.
    $nistTitles = @{}
    if (Get-Command Get-NRGNISTControlTitle -ErrorAction SilentlyContinue) {
        foreach ($c in $cdefs.Values) {
            $ref = [string](Get-NRGNestedProperty -Object $c -Path 'References.NIST' -Default '')
            # No trailing \b: after the ')' of an enhancement there is no
            # word boundary, so '\b[A-Z]{2}-\d+(\(\d+\))?\b' matches only
            # 'IA-2' out of 'IA-2(1)' and silently drops every enhancement.
            foreach ($m in [regex]::Matches($ref, '\b[A-Z]{2}-\d+(?:\(\d+\))?')) {
                $nid = $m.Value
                if ($nistTitles.ContainsKey($nid)) { continue }
                $t = [string](Get-NRGNISTControlTitle -ControlId $nid)
                # Only real titles. A lookup that echoes the identifier back is
                # a miss, and storing it would render "AC-2 AC-2" in the sheet.
                if ($t -and $t -ne $nid) { $nistTitles[$nid] = $t }
            }
        }
    }

    # Build serializable data payload
    $matrixLicProfile = $null
    if (Get-Command Get-NRGTenantLicenseProfile -ErrorAction SilentlyContinue) {
        try { $matrixLicProfile = Get-NRGTenantLicenseProfile } catch { $matrixLicProfile = $null }
    }
    $matrixLicKnown = [bool](Get-NRGObjectField -Item $matrixLicProfile -Key 'HasLicenseData' -Default $false)
    $payload = @{
        NistTitles = $nistTitles
        # Get-NRGObjectField, not dot-access-then-??: under StrictMode a missing
        # key THROWS before ?? can supply the default, so `$Metadata.Operator ??
        # ''` aborts the whole publisher whenever Operator is absent. It is
        # absent on the -FromResults replay path, whose fallback metadata carries
        # only TenantDomain / AssessmentDate / ToolVersion — and the caller wraps
        # this in a try/catch that degrades to a warning, so the XLSX silently
        # was not produced rather than failing loudly.
        Metadata = @{
            TenantDomain   = [string](Get-NRGObjectField -Item $Metadata -Key 'TenantDomain'   -Default 'Unknown')
            AssessmentDate = [string](Get-NRGObjectField -Item $Metadata -Key 'AssessmentDate' -Default (Get-Date -Format 'yyyy-MM-dd'))
            ToolVersion    = [string](Get-NRGObjectField -Item $Metadata -Key 'ToolVersion'    -Default '4.5.5')
            Operator       = [string](Get-NRGObjectField -Item $Metadata -Key 'Operator'       -Default '')
        }
        Findings = @($Findings | ForEach-Object {
            $ctrl = $cdefs[$_.ControlId]
            $licReqStr = [string](Get-NRGObjectField -Item $ctrl -Key 'LicenseRequirement' -Default 'Included')
            @{
                ControlId       = [string]$_.ControlId
                Title           = [string]$_.Title
                Category        = [string]$_.Category
                State           = [string]$_.State
                Severity        = [string]$_.Severity
                Detail          = [string]$_.Detail
                CurrentValue    = [string](Get-NRGObjectField -Item $_ -Key 'CurrentValue'  -Default '')
                RequiredValue   = [string](Get-NRGObjectField -Item $_ -Key 'RequiredValue' -Default '')
                Remediation     = [string]$(
                    # Get-NRGObjectField, not dot-access-then-??: $ctrl is the
                    # controls.json definition and $_ is the finding — either can
                    # be a replayed/deserialized object that predates this field,
                    # and under StrictMode a missing member throws before ?? can
                    # apply (the "XLSX publish failed: Remediation cannot be
                    # found" warning on every run).
                    $rem = Get-NRGObjectField -Item $ctrl -Key 'Remediation' -Default ''
                    if (-not $rem) { $rem = Get-NRGObjectField -Item $_ -Key 'Remediation' -Default '' }
                    $rem
                )
                # $ctrl is $null for DEV-* endpoint findings (device-controls.json,
                # not controls.json), and under StrictMode Latest a member read on
                # $null throws before ?? applies — which aborted the whole XLSX.
                BusinessRisk    = [string](Get-NRGObjectField -Item $ctrl -Key 'BusinessRisk' -Default '')
                LicenseReq      = $licReqStr
                # The License Gaps sheet lists only controls whose license the
                # tenant does NOT hold, decided by the same per-control test the
                # score uses. It listed every Gap with a non-"Included"
                # requirement, so a Business Premium tenant was told it lacked
                # Business Premium. Unknown licensing blocks nothing.
                LicenseBlocked  = [bool]($matrixLicKnown -and $licReqStr -notmatch '^Included' -and
                                   -not (Test-NRGLicenseRequirementMet -LicenseRequirement $licReqStr -LicenseProfile $matrixLicProfile -ControlId ([string]$_.ControlId)))
                FrameworkIds    = @(Get-NRGObjectField -Item $_ -Key 'FrameworkIds' -Default @() | ForEach-Object { [string]$_ })
                CIS             = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.CIS'      -Default '')
                SCuBA           = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.SCuBA'    -Default '')
                NIST            = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.NIST'     -Default '')
                CMMC            = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.CMMC'     -Default '')
                ISO27001        = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.ISO27001' -Default '')
                SOC2            = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.SOC2'     -Default '')
                HIPAA           = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.HIPAA'    -Default '')
                PCIDSS          = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.PCIDSS'   -Default '')
                DISASTIG        = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.DISASTIG' -Default '')
                MITRE           = [string]((Get-NRGNestedProperty -Object $ctrl -Path 'References.MITRE' -Default @()) -join ', ')
            }
        })
    }

    # Physical / media / device 800-53 controls. This is the sheet an assessor
    # actually works down while collecting off-tenant evidence, so it belongs in
    # the spreadsheet deliverable rather than only in the HTML report. Flattened
    # here (not in Python) so the scope and status semantics have exactly one
    # implementation — Lib/Get-NRGNISTPhysicalPosture.ps1.
    $payload.NistPhysical = @()
    if (Get-Command Get-NRGNISTPhysicalPosture -ErrorAction SilentlyContinue) {
        try {
            $phys = Get-NRGNISTPhysicalPosture -Findings $Findings
            if ($phys -and $phys.Available) {
                $payload.NistPhysical = @(foreach ($grp in $phys.Groups) {
                    foreach ($it in $grp.Items) {
                        @{
                            Group             = [string]$grp.Title
                            NistControl       = [string]$it.NistControl
                            NistTitle         = [string]$it.NistTitle
                            Scope             = [string]$it.Scope
                            Status            = [string]$it.Status
                            DeviceAspect      = [string]$it.DeviceAspect
                            Evidence          = [string](@($it.Evidence | ForEach-Object { "$($_.ControlId) ($($_.State))" }) -join ', ')
                            OffTenantEvidence = [string]$it.OffTenantEvidence
                            Options           = [string](@($it.Options) -join "`n")
                        }
                    }
                })
            }
        } catch {
            Write-Verbose "NIST physical posture unavailable for the matrix: $($_.Exception.Message)"
        }
    }

    # Serialize JSON for the Python helper.
    # Audit fix (v4.6.x MED #4): the previous implementation wrote tenant
    # findings to $env:TEMP via [System.IO.Path]::GetTempFileName(), which
    # creates the file with default inherited permissions before any ACL
    # tightening can run. Two-step (create + chmod) is race-prone in a
    # shared TEMP. Instead, co-locate the helper JSON next to the XLSX
    # output (which already lives in the ACL-hardened output directory)
    # and harden it via Set-NRGSensitiveFileAcl as soon as we write it.
    $outputDir = Split-Path -Parent $OutputPath
    if (-not $outputDir -or -not (Test-Path -LiteralPath $outputDir)) {
        $outputDir = [System.IO.Path]::GetTempPath()
    }
    $matrixBase = [System.IO.Path]::GetFileNameWithoutExtension($OutputPath)
    if ([string]::IsNullOrWhiteSpace($matrixBase)) { $matrixBase = 'compliance-matrix' }
    $tmpJson = Join-Path $outputDir "$matrixBase-matrix-input.json"
    try {
        # Publisher self-hardens via Set-NRGSensitiveFileContent: the file is
            # pre-created and its ACL applied BEFORE tenant data lands. Writing with a
            # bare Out-File lets the file inherit the parent directory ACL for the
            # duration of the write, which on a shared MSP workstation or a synced
            # OneDrive folder is a window in which a co-resident process can read CA
            # policies, admin UPNs, OAuth grants and DMARC records. Hardening travels
            # with the terminal write so no caller can forget it. The Out-File fallback
            # preserves behavior if Lib/ has not been dot-sourced.
        if (Get-Command Set-NRGSensitiveFileContent -ErrorAction SilentlyContinue) {
            Set-NRGSensitiveFileContent -Path $tmpJson -Content ($payload | ConvertTo-Json -Depth 6 -Compress)
        } else {
            $payload | ConvertTo-Json -Depth 6 -Compress | Out-File -LiteralPath $tmpJson -Encoding utf8
            if (Get-Command Set-NRGSensitiveFileAcl -ErrorAction SilentlyContinue) {
                Set-NRGSensitiveFileAcl -Path $tmpJson -ErrorAction SilentlyContinue
            }
        }
        if (Get-Command Set-NRGSensitiveFileAcl -ErrorAction SilentlyContinue) {
            Set-NRGSensitiveFileAcl -Path $tmpJson -ErrorAction SilentlyContinue
        }

        # Embedded Python — reads JSON, writes XLSX, no string interpolation of tenant data
        $pyScript = @'
import json, re, sys, os
from openpyxl import Workbook
from openpyxl.styles import (Font, PatternFill, Alignment, Border, Side,
                              GradientFill)
from openpyxl.utils import get_column_letter

data_path = sys.argv[1]
out_path  = sys.argv[2]

with open(data_path, encoding='utf-8') as f:
    d = json.load(f)

# Official Rev 5 control titles, supplied by the PowerShell side from
# Config/nist-800-53-catalog.json. A bare "AC-2, AC-3" only tells a reader
# which controls were exercised if they already know 800-53 by heart.
NIST_TITLES = d.get('NistTitles', {}) or {}

def nist_label(nid):
    """'AC-2 Account Management', or the bare id when the catalog has no
    entry. A missing title must never delete the identifier from the row."""
    t = NIST_TITLES.get(nid, '')
    return ('%s %s' % (nid, t)) if t else nid


meta     = d['Metadata']
findings = d['Findings']
# One verdict per control for every SCORE on this workbook (worst instance:
# Gap > Error > Partial > Satisfied > NotApplicable), matching
# Get-NRGCoverageScore. DNS emits one finding per domain; scoring each would
# weight a DNS control once per domain. Row listings still use `findings`.
_rank = {'Gap': 5, 'Error': 4, 'Partial': 3, 'Satisfied': 2, 'NotApplicable': 1}
_worst = {}
for _f in findings:
    _c = _f.get('ControlId', '')
    if _c not in _worst or _rank.get(_f['State'], 0) > _rank.get(_worst[_c]['State'], 0):
        _worst[_c] = _f
scoring = list(_worst.values())

# ── Color palette ─────────────────────────────────────────────────────────────
NAVY    = '0F2544'
ORANGE  = 'E8621A'
BLUE    = '3B7DD8'
WHITE   = 'FFFFFF'
LGRAY   = 'F4F7FB'
MGRAY   = 'E2E8F0'
DGRAY   = '6B7280'
RED     = 'DC2626'
AMBER   = 'CA8A04'
GREEN   = '059669'
ROSE    = 'FEF2F2'
AMBER_L = 'FFFBEB'
GREEN_L = 'F0FDF4'
NA_L    = 'F9FAFB'

SEV_COLORS = {'Critical':'DC2626','High':'EA580C','Medium':'CA8A04','Low':'65A30D','Informational':'6B7280'}
STATE_COLORS = {'Gap':ROSE,'Partial':AMBER_L,'Satisfied':GREEN_L,'NotApplicable':NA_L}
STATE_FONT   = {'Gap':'991B1B','Partial':'92400E','Satisfied':'166534','NotApplicable':'6B7280'}

# CWE-345 / OWASP A03 — XLSX formula-injection guard. Finding fields
# (Detail, CurrentValue, Remediation, Title) can carry attacker-influenced
# strings — a value like "=cmd|'/c calc'!A1" written verbatim to a cell
# becomes a live formula when the operator opens the workbook. Prefix
# formula-leading cells with an apostrophe (Excel-standard neutralization)
# and force string data_type so openpyxl never auto-detects a formula.
_FORMULA_LEAD = ('=', '+', '-', '@', '\t', '\r')

def _safe(val):
    # Numeric values (including bool, which subclasses int) pass through
    # unchanged so Excel renders them as numbers — sorting, formatting,
    # and aggregation in the operator's workbook depend on it.
    if val is None: return ''
    if isinstance(val, (int, float)):
        return val
    s = str(val)
    if s and s[0] in _FORMULA_LEAD:
        return "'" + s
    return s

def hdr(ws, row, col, val, bg=NAVY, fg=WHITE, bold=True, wrap=False, size=10):
    safe_val = _safe(val)
    c = ws.cell(row=row, column=col, value=safe_val)
    if isinstance(safe_val, str):
        c.data_type = 's'
    c.font = Font(name='Arial', bold=bold, color=fg, size=size)
    c.fill = PatternFill('solid', fgColor=bg)
    c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=wrap)
    return c

def cell(ws, row, col, val, bg=None, fg='111827', bold=False, wrap=True, align='left'):
    safe_val = _safe(val)
    c = ws.cell(row=row, column=col, value=safe_val)
    if isinstance(safe_val, str):
        c.data_type = 's'
    c.font = Font(name='Arial', color=fg, bold=bold, size=9)
    if bg: c.fill = PatternFill('solid', fgColor=bg)
    c.alignment = Alignment(horizontal=align, vertical='top', wrap_text=wrap)
    return c

def thin_border(ws, row, col):
    t = Border(
        left=Side(style='thin',color='E2E8F0'),
        right=Side(style='thin',color='E2E8F0'),
        top=Side(style='thin',color='E2E8F0'),
        bottom=Side(style='thin',color='E2E8F0')
    )
    ws.cell(row=row, column=col).border = t

wb = Workbook()

# ═══════════════════════════════════════════════════════════════════════
# SHEET 1: SUMMARY
# ═══════════════════════════════════════════════════════════════════════
ws = wb.active
ws.title = 'Summary'
ws.sheet_view.showGridLines = False
ws.column_dimensions['A'].width = 28
ws.column_dimensions['B'].width = 18
ws.column_dimensions['C'].width = 22
ws.column_dimensions['D'].width = 18

# Title banner
ws.row_dimensions[1].height = 36
ws.merge_cells('A1:D1')
t = ws['A1']
t.value = f"M365 Security Assessment — {meta['TenantDomain']}"
t.font = Font(name='Arial', bold=True, size=16, color=WHITE)
t.fill = PatternFill('solid', fgColor=NAVY)
t.alignment = Alignment(horizontal='center', vertical='center')

ws.merge_cells('A2:D2')
s = ws['A2']
s.value = f"Generated: {meta['AssessmentDate']}  |  Tool: NRG-Assessment v{meta['ToolVersion']}"
s.font = Font(name='Arial', size=9, color='6B7280')
s.alignment = Alignment(horizontal='center')

# Score section
total = len(scoring)
gaps  = sum(1 for f in scoring if f['State']=='Gap')
parts = sum(1 for f in scoring if f['State']=='Partial')
sats  = sum(1 for f in scoring if f['State']=='Satisfied')
nas   = sum(1 for f in scoring if f['State']=='NotApplicable')
# Errors are scored as failures (they sit in the denominator), so the summary
# MUST name them: without the row a reader adds Satisfied + Partial + Gaps,
# comes up short of the stated Assessed count, and cannot tell whether the
# missing rows were passes or failures.
errs  = sum(1 for f in scoring if f['State']=='Error')
scored = total - nas
score  = round(100*(sats+0.5*parts)/scored) if scored else 0
posture = 'Strong' if score>=85 else 'Moderate' if score>=65 else 'At Risk' if score>=40 else 'Critical Risk'

hdr(ws,4,1,'Metric',NAVY,WHITE); hdr(ws,4,2,'Value',NAVY,WHITE); hdr(ws,4,3,'Metric',NAVY,WHITE); hdr(ws,4,4,'Value',NAVY,WHITE)
rows4 = [
    ('Security Score', f'{score}/100', 'Posture', posture),
    ('Total Controls', total,          'Gaps',    gaps),
    ('Satisfied',      sats,           'Partial', parts),
    ('Errors',         errs,           'Not Applicable', nas),
    ('Assessed',       scored,         'Total States', f'{sats}+{parts}+{gaps}+{errs}+{nas}={sats+parts+gaps+errs+nas}'),
]
for i,(l1,v1,l2,v2) in enumerate(rows4,5):
    cell(ws,i,1,l1,LGRAY,NAVY,True)
    cell(ws,i,2,v1,WHITE,'111827',True,align='center')
    cell(ws,i,3,l2,LGRAY,NAVY,True)
    cell(ws,i,4,v2,WHITE,'111827',True,align='center')
    ws.row_dimensions[i].height = 18

# Severity breakdown
ws.merge_cells('A10:D10')
hdr(ws,10,1,'Gap Severity Breakdown',ORANGE,WHITE)
sev_hdr = ['Critical','High','Medium','Low']
for j,s2 in enumerate(sev_hdr,1):
    hdr(ws,11,j,s2,SEV_COLORS[s2],WHITE,size=9)
    cnt = sum(1 for f in scoring if f['State']=='Gap' and f['Severity']==s2)
    cell(ws,12,j,cnt,WHITE,SEV_COLORS[s2],True,align='center')

# Workload scores
ws.merge_cells('A14:D14')
hdr(ws,14,1,'Score by Workload',BLUE,WHITE)
hdr(ws,15,1,'Workload',MGRAY,NAVY); hdr(ws,15,2,'Score',MGRAY,NAVY); hdr(ws,15,3,'Gaps',MGRAY,NAVY); hdr(ws,15,4,'Controls',MGRAY,NAVY)
wl_names={'AAD':'Identity & Access','EXO':'Exchange Online','DNS':'DNS Email Auth','DEF':'Microsoft Defender',
          'SPO':'SharePoint/OneDrive','TMS':'Microsoft Teams','INT':'Intune/Endpoint','PVW':'Purview/Compliance','PPL':'Power Platform'}
from collections import defaultdict
wl_groups = defaultdict(list)
for f in scoring:
    wl = f['ControlId'].split('-')[0]
    wl_groups[wl].append(f)
row=16
for wl in ['AAD','EXO','DEF','DNS','SPO','TMS','INT','PVW','PPL']:
    grp = wl_groups.get(wl,[])
    if not grp: continue
    wn  = sum(1 for f in grp if f['State']!='NotApplicable')
    ws2 = sum(1 for f in grp if f['State']=='Satisfied')
    wp2 = sum(1 for f in grp if f['State']=='Partial')
    wg2 = sum(1 for f in grp if f['State']=='Gap')
    wsc = round(100*(ws2+0.5*wp2)/wn) if wn else 0
    col2= GREEN if wsc>=85 else AMBER if wsc>=65 else 'EA580C' if wsc>=40 else RED
    cell(ws,row,1,wl_names.get(wl,wl),LGRAY,NAVY)
    cell(ws,row,2,f'{wsc}/100',WHITE,col2,True,align='center')
    cell(ws,row,3,wg2,WHITE,RED if wg2>0 else GREEN,True,align='center')
    cell(ws,row,4,len(grp),WHITE,'111827',align='center')
    ws.row_dimensions[row].height = 16
    row+=1

# Framework scores
fws = {'CIS':'CIS M365 v6.0.1','SCuBA':'CISA SCuBA','NIST':'NIST 800-53r5','CMMC':'CMMC 2.0 L2',
       'ISO27001':'ISO 27001:2022','SOC2':'SOC 2','HIPAA':'HIPAA §164','PCIDSS':'PCI DSS v4.0'}
ws.merge_cells(f'A{row+1}:D{row+1}')
hdr(ws,row+1,1,'Framework Compliance',NAVY,WHITE)
hdr(ws,row+2,1,'Framework',MGRAY,NAVY); hdr(ws,row+2,2,'Score',MGRAY,NAVY)
hdr(ws,row+2,3,'Mapped Controls',MGRAY,NAVY); hdr(ws,row+2,4,'Reference',MGRAY,NAVY)
row+=3
for fw, fname in fws.items():
    ff = [f for f in scoring if any(fid.startswith(fw + ':') for fid in f['FrameworkIds'])]
    fd = [f for f in ff if f['State']!='NotApplicable']
    fs = sum(1 for f in fd if f['State']=='Satisfied')
    fp = sum(1 for f in fd if f['State']=='Partial')
    fsc= round(100*(fs+0.5*fp)/len(fd)) if fd else 0
    fcol=GREEN if fsc>=85 else AMBER if fsc>=65 else 'EA580C' if fsc>=40 else RED
    cell(ws,row,1,fname,LGRAY,NAVY); cell(ws,row,2,f'{fsc}%',WHITE,fcol,True,align='center')
    cell(ws,row,3,len(fd),WHITE,'111827',align='center'); cell(ws,row,4,fw,WHITE,DGRAY)
    ws.row_dimensions[row].height=16; row+=1

# ═══════════════════════════════════════════════════════════════════════
def build_findings_sheet(wb, title, rows, columns):
    ws2 = wb.create_sheet(title)
    ws2.sheet_view.showGridLines = False
    ws2.freeze_panes = 'A3'
    # Banner
    ws2.merge_cells(f'A1:{get_column_letter(len(columns))}1')
    t2 = ws2['A1']
    t2.value = f'{title} — {meta["TenantDomain"]}'
    t2.font = Font(name='Arial', bold=True, size=11, color=WHITE)
    t2.fill = PatternFill('solid', fgColor=NAVY)
    t2.alignment = Alignment(horizontal='center', vertical='center')
    ws2.row_dimensions[1].height = 26
    # Headers
    for j,(col_name,width) in enumerate(columns,1):
        hdr(ws2, 2, j, col_name, ORANGE, WHITE, size=9)
        ws2.column_dimensions[get_column_letter(j)].width = width
    ws2.row_dimensions[2].height = 18
    # Data
    for i,row2 in enumerate(rows,3):
        bg = STATE_COLORS.get(row2.get('State',''),'')
        fg_state = STATE_FONT.get(row2.get('State',''),'111827')
        ws2.row_dimensions[i].height = max(15, min(60, 10 + len(str(row2.get('Detail','')))/8))
        for j,(col_name,_) in enumerate(columns,1):
            key = col_name.replace(' ','').replace('/','')
            val = row2.get(col_name, row2.get(key, ''))
            fg2 = fg_state if col_name == 'State' else ('111827' if col_name not in ('Severity',) else SEV_COLORS.get(str(val),'111827'))
            c2 = cell(ws2, i, j, val, bg, fg2, bold=(col_name=='State'))
            thin_border(ws2, i, j)
    # Auto-filter
    ws2.auto_filter.ref = f'A2:{get_column_letter(len(columns))}{len(rows)+2}'
    return ws2

ALL_COLS = [
    ('Control ID',18),('Title',36),('Category',14),('State',12),
    ('Severity',10),('Current Value',22),('Required Value',22),
    ('Business Risk',36),('Remediation',40),('CIS',12),('SCuBA',16),
    ('NIST',14),('CMMC',14),('ISO 27001',14),('SOC 2',14),('HIPAA',14),
    ('License',28),('MITRE',20),
]

def map_row(f):
    return {
        'Control ID': f['ControlId'], 'Title': f['Title'], 'Category': f['Category'],
        'State': f['State'], 'Severity': f['Severity'],
        'Current Value': f['CurrentValue'], 'Required Value': f['RequiredValue'],
        'Business Risk': f['BusinessRisk'], 'Remediation': f['Remediation'],
        'CIS': f['CIS'], 'SCuBA': f['SCuBA'], 'NIST': f['NIST'], 'CMMC': f['CMMC'],
        'ISO 27001': f.get('ISO27001',''), 'SOC 2': f.get('SOC2',''),
        'HIPAA': f.get('HIPAA',''), 'License': f['LicenseReq'], 'MITRE': f['MITRE'],
        'Detail': f['Detail'],
    }

all_rows  = [map_row(f) for f in sorted(findings, key=lambda x:(
    ['Gap','Partial','Satisfied','NotApplicable'].index(x['State']) if x['State'] in
    ['Gap','Partial','Satisfied','NotApplicable'] else 9, x['ControlId']))]
gap_rows  = [r for r in all_rows if r['State'] in ('Gap','Partial')]

# Sheet 2: All Controls
build_findings_sheet(wb, 'All Controls', all_rows, ALL_COLS)

# Sheet 3: Gaps Only
build_findings_sheet(wb, 'Gaps & Partials', gap_rows, ALL_COLS)

# Framework-specific sheets
FW_SHEETS = [
    ('CIS M365 v6', 'CIS',      'CIS',       [('Control ID',16),('Title',36),('State',12),('Severity',10),('CIS Ref',14),('Remediation',40)]),
    ('CISA SCuBA',  'SCuBA',    'SCuBA',      [('Control ID',16),('Title',36),('State',12),('Severity',10),('SCuBA Ref',18),('Remediation',40)]),
    ('NIST 800-53', 'NIST',     'NIST',       [('Control ID',16),('Title',36),('State',12),('Severity',10),('NIST Ref',64),('Business Risk',40)]),
    ('CMMC 2.0',    'CMMC',     'CMMC',       [('Control ID',16),('Title',36),('State',12),('Severity',10),('CMMC Ref',14),('Remediation',40)]),
    ('ISO 27001',   'ISO27001', 'ISO 27001',  [('Control ID',16),('Title',36),('State',12),('Severity',10),('ISO Ref',14),('Remediation',40)]),
    ('SOC 2',       'SOC2',     'SOC 2',      [('Control ID',16),('Title',36),('State',12),('Severity',10),('SOC2 Ref',14),('Remediation',40)]),
    ('HIPAA §164',  'HIPAA',    'HIPAA',      [('Control ID',16),('Title',36),('State',12),('Severity',10),('HIPAA Ref',14),('Remediation',40)]),
]
for sheet_title, fw_key, ref_col_name, cols in FW_SHEETS:
    fw_rows = []
    for f in findings:
        ref = f.get(fw_key,'') or (f.get('ISO27001','') if fw_key=='ISO27001' else '') or \
              (f.get('SOC2','') if fw_key=='SOC2' else '') or \
              (f.get('HIPAA','') if fw_key=='HIPAA' else '')
        if not ref: continue
        # NIST only: resolve each identifier in the citation to its official
        # Rev 5 title. "IA-2, IA-5(1)" is meaningless to anyone not carrying
        # 800-53 in their head, and this sheet is the one an auditor reads.
        # Every other framework's ref is left verbatim — a CIS or SCuBA id is
        # already the whole reference.
        if fw_key == 'NIST':
            # No trailing \b — after the ')' of an enhancement there is no word
            # boundary, so the anchored form matches only 'IA-2' out of
            # 'IA-2(1)' and drops the enhancement. Deduplicated in order: a
            # citation listing IA-2 and IA-2(1) must not render IA-2 twice.
            ids, seen = [], set()
            for x in re.findall(r'\b[A-Z]{2}-\d+(?:\(\d+\))?', ref):
                if x not in seen:
                    seen.add(x); ids.append(x)
            if ids:
                ref = '; '.join(nist_label(x) for x in ids)
        fw_rows.append({
            'Control ID': f['ControlId'], 'Title': f['Title'],
            'State': f['State'], 'Severity': f['Severity'],
            f'{ref_col_name} Ref': ref, 'Remediation': f['Remediation'],
            'Business Risk': f['BusinessRisk'], 'Detail': f['Detail'],
        })
    fw_rows.sort(key=lambda x:['Gap','Partial','Satisfied','NotApplicable'].index(x['State'])
                 if x['State'] in ['Gap','Partial','Satisfied','NotApplicable'] else 9)
    if fw_rows:
        build_findings_sheet(wb, sheet_title, fw_rows, cols)

# NIST physical / media / device sheet — the checklist an assessor works down
# while collecting evidence that does not exist inside the tenant. Flattened by
# the PowerShell side so scope and status semantics have one implementation.
# Absent from older replayed result JSON, hence the .get() default.
phys_rows = []
for p in d.get('NistPhysical', []) or []:
    phys_rows.append({
        'Group': p.get('Group',''),
        'NIST Ref': p.get('NistControl',''),
        'Control': p.get('NistTitle',''),
        'Scope': p.get('Scope',''),
        'Status': p.get('Status',''),
        'Device Aspect': p.get('DeviceAspect',''),
        'Tenant Evidence': p.get('Evidence',''),
        'Evidence to Collect': p.get('OffTenantEvidence',''),
        'Implementation Options': p.get('Options',''),
        # Not a rendered column — build_findings_sheet sizes the row from it.
        'Detail': p.get('Options',''),
    })
if phys_rows:
    build_findings_sheet(wb, 'NIST Physical & Device', phys_rows,
        [('Group',26),('NIST Ref',11),('Control',34),('Scope',11),('Status',20),
         ('Device Aspect',52),('Tenant Evidence',30),('Evidence to Collect',52),
         ('Implementation Options',64)])

# NIST 800-53 control-family rollup sheet.
# The 'NIST 800-53' sheet above lists findings; this one aggregates them by
# 800-53 control FAMILY, which is the unit an 800-53 / FedRAMP / CMMC reader
# organizes their own POA&M around. A finding citing controls in two families
# counts in both, so Assessed does not sum to the assessment total.
NIST_FAMILY_NAMES = {
    'AC':'Access Control','AT':'Awareness and Training','AU':'Audit and Accountability',
    'CA':'Assessment, Authorization, and Monitoring','CM':'Configuration Management',
    'CP':'Contingency Planning','IA':'Identification and Authentication',
    'IR':'Incident Response','MA':'Maintenance','MP':'Media Protection',
    'PE':'Physical and Environmental Protection','PL':'Planning',
    'PM':'Program Management','PS':'Personnel Security',
    'PT':'PII Processing and Transparency','RA':'Risk Assessment',
    'SA':'System and Services Acquisition','SC':'System and Communications Protection',
    'SI':'System and Information Integrity','SR':'Supply Chain Risk Management',
}
NIST_REF_RE = re.compile(r'^([A-Z]{2})-(\d{1,3})(\(\d{1,3}\))?$')

fam_findings = {}
fam_refs     = {}
for f in scoring:
    raw = f.get('NIST','') or ''
    fams_here, refs_here = set(), set()
    for tok in str(raw).split(','):
        m = NIST_REF_RE.match(tok.strip())
        if not m: continue
        fams_here.add(m.group(1))
        refs_here.add('%s-%d%s' % (m.group(1), int(m.group(2)), m.group(3) or ''))
    for fam in fams_here:
        fam_findings.setdefault(fam, []).append(f)
        fam_refs.setdefault(fam, set()).update(
            r for r in refs_here if r.split('-')[0] == fam)

nist_fam_rows = []
for fam in sorted(fam_findings):
    grp   = fam_findings[fam]
    sat   = sum(1 for x in grp if x['State'] == 'Satisfied')
    part  = sum(1 for x in grp if x['State'] == 'Partial')
    gap   = sum(1 for x in grp if x['State'] == 'Gap')
    na    = sum(1 for x in grp if x['State'] == 'NotApplicable')
    err   = sum(1 for x in grp if x['State'] == 'Error')
    # Same denominator rule as Get-NRGCoverageScore -ErrorHandling Gap:
    # NotApplicable is excluded, Error counts as a soft gap.
    scored = len(grp) - na
    # A family assessed only through NotApplicable findings has no denominator.
    # Report that as "Not assessed", never as 0% — 0% is a failing grade for a
    # question the tool never got to ask.
    cov    = ('%d%%' % round(100.0 * (sat + 0.5 * part) / scored)) if scored > 0 else 'Not assessed'
    nist_fam_rows.append({
        'Family': fam,
        'Family Name': NIST_FAMILY_NAMES.get(fam, fam),
        'Assessed': len(grp), 'Met': sat, 'Partial': part, 'Gap': gap,
        'N/A': na, 'Error': err, 'Coverage': cov,
        '800-53 Controls': '; '.join(nist_label(x) for x in sorted(fam_refs.get(fam, set()))),
    })
if nist_fam_rows:
    build_findings_sheet(wb, 'NIST Families', nist_fam_rows,
        [('Family',10),('Family Name',40),('Assessed',10),('Met',8),('Partial',9),
         ('Gap',8),('N/A',8),('Error',8),('Coverage',13),('800-53 Controls',88)])

# License gaps sheet
lic_rows = [map_row(f) for f in findings if f['State'] in ('Gap','NotApplicable') and f.get('LicenseBlocked')]
if lic_rows:
    build_findings_sheet(wb, 'License Gaps', lic_rows,
        [('Control ID',16),('Title',36),('State',12),('Severity',10),('License',32),('Remediation',40)])

wb.save(out_path)
print(f"XLSX saved: {out_path}")
'@

        # Audit fix (v4.6.x MED #4): py helper also co-located with the XLSX
        # output. The Python source itself isn't tenant-sensitive, but keeping
        # all generation artifacts in one ACL-hardened directory simplifies
        # cleanup and removes the TEMP-race surface entirely.
        $pyTmp = Join-Path $outputDir "$matrixBase-matrix-helper.py"
        try {
            $pyScript | Out-File -LiteralPath $pyTmp -Encoding utf8
            $result = & $pythonCmd $pyTmp $tmpJson $OutputPath 2>&1
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "XLSX generation failed: $result"
            } else {
                Write-Verbose "XLSX: $result"
            }
        } finally {
            Remove-Item -LiteralPath $pyTmp -ErrorAction SilentlyContinue
        }
    } finally {
        Remove-Item -LiteralPath $tmpJson -ErrorAction SilentlyContinue
    }
}
