#Requires -Version 7.0
#
# Publish-NRGComplianceMatrix.ps1  (v4.5.5)
# Generates a professional XLSX compliance matrix from assessment findings.
#
# Sheets:
#   1. Summary        — Overall posture, score, workload breakdown, framework scores
#   2. All Controls   — Every control with status, severity, framework citations
#   3. Gaps Only      — Filtered to Gap/Partial, with remediation commands
#   4. CIS M365 v6    — Controls mapped to CIS sections
#   5. CISA SCuBA     — Controls mapped to SCuBA policy IDs
#   6. NIST 800-53    — Controls mapped to NIST control families
#   7. CMMC 2.0       — Controls mapped to CMMC practices
#   8. ISO 27001      — Controls mapped to ISO 27001:2022 clauses
#   9. SOC 2          — Controls mapped to Trust Services Criteria
#  10. HIPAA          — Controls mapped to HIPAA §164 safeguards
#  11. License Gaps   — Controls blocked by current license tier
#
# The XLSX is generated by calling an embedded Python script that uses openpyxl.
# This avoids requiring Excel or COM automation on the assessment machine.
#
# SECURITY: No tenant data is interpolated into Python code.
#           All data passes through JSON serialization → Python reads the JSON.
#

function Publish-NRGComplianceMatrix {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [hashtable] $Metadata,
        [Parameter(Mandatory)] [object[]]  $Findings,
        [Parameter(Mandatory)]
        [ValidateScript({
            if ($_ -match '\.\.[\\\/]') { throw 'Path traversal not allowed.' }
            return $true
        })]
        [string] $OutputPath
    )

    # Verify Python + openpyxl available
    $pythonCmd = $null
    foreach ($py in @('python3','python')) {
        try {
            $null = & $py -c 'import openpyxl' 2>&1
            if ($LASTEXITCODE -eq 0) { $pythonCmd = $py; break }
        } catch { }
    }
    if (-not $pythonCmd) {
        Write-Warning "openpyxl not available — skipping XLSX output. Install: pip install openpyxl"
        return
    }

    # Load control definitions for framework citations + license info
    $cdefs = @{}
    try { foreach ($c in (Get-NRGControlDefinitions)) { $cdefs[$c.ControlId] = $c } } catch { }

    # Build serializable data payload
    $payload = @{
        Metadata = @{
            TenantDomain   = [string]($Metadata.TenantDomain  ?? 'Unknown')
            AssessmentDate = [string]($Metadata.AssessmentDate ?? (Get-Date -Format 'yyyy-MM-dd'))
            ToolVersion    = [string]($Metadata.ToolVersion    ?? '4.5.5')
            Operator       = [string]($Metadata.Operator       ?? '')
        }
        Findings = @($Findings | ForEach-Object {
            $ctrl = $cdefs[$_.ControlId]
            @{
                ControlId       = [string]$_.ControlId
                Title           = [string]$_.Title
                Category        = [string]$_.Category
                State           = [string]$_.State
                Severity        = [string]$_.Severity
                Detail          = [string]$_.Detail
                CurrentValue    = [string]($_.CurrentValue  ?? '')
                RequiredValue   = [string]($_.RequiredValue ?? '')
                Remediation     = [string]($ctrl.Remediation ?? $_.Remediation ?? '')
                BusinessRisk    = [string]($ctrl.BusinessRisk ?? '')
                LicenseReq      = [string]($ctrl.LicenseRequirement ?? 'Included')
                FrameworkIds    = @($_.FrameworkIds ?? @() | ForEach-Object { [string]$_ })
                CIS             = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.CIS'      -Default '')
                SCuBA           = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.SCuBA'    -Default '')
                NIST            = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.NIST'     -Default '')
                CMMC            = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.CMMC'     -Default '')
                ISO27001        = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.ISO27001' -Default '')
                SOC2            = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.SOC2'     -Default '')
                HIPAA           = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.HIPAA'    -Default '')
                PCIDSS          = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.PCIDSS'   -Default '')
                DISASTIG        = [string](Get-NRGNestedProperty -Object $ctrl -Path 'References.DISASTIG' -Default '')
                MITRE           = [string]((Get-NRGNestedProperty -Object $ctrl -Path 'References.MITRE' -Default @()) -join ', ')
            }
        })
    }

    # Serialize JSON for the Python helper.
    # Audit fix (v4.6.x MED #4): the previous implementation wrote tenant
    # findings to $env:TEMP via [System.IO.Path]::GetTempFileName(), which
    # creates the file with default inherited permissions before any ACL
    # tightening can run. Two-step (create + chmod) is race-prone in a
    # shared TEMP. Instead, co-locate the helper JSON next to the XLSX
    # output (which already lives in the ACL-hardened output directory)
    # and harden it via Set-NRGSensitiveFileAcl as soon as we write it.
    $outputDir = Split-Path -Parent $OutputPath
    if (-not $outputDir -or -not (Test-Path -LiteralPath $outputDir)) {
        $outputDir = [System.IO.Path]::GetTempPath()
    }
    $matrixBase = [System.IO.Path]::GetFileNameWithoutExtension($OutputPath)
    if ([string]::IsNullOrWhiteSpace($matrixBase)) { $matrixBase = 'compliance-matrix' }
    $tmpJson = Join-Path $outputDir "$matrixBase-matrix-input.json"
    try {
        $payload | ConvertTo-Json -Depth 6 -Compress | Out-File -LiteralPath $tmpJson -Encoding utf8
        if (Get-Command Set-NRGSensitiveFileAcl -ErrorAction SilentlyContinue) {
            Set-NRGSensitiveFileAcl -Path $tmpJson -ErrorAction SilentlyContinue
        }

        # Embedded Python — reads JSON, writes XLSX, no string interpolation of tenant data
        $pyScript = @'
import json, sys, os
from openpyxl import Workbook
from openpyxl.styles import (Font, PatternFill, Alignment, Border, Side,
                              GradientFill)
from openpyxl.utils import get_column_letter

data_path = sys.argv[1]
out_path  = sys.argv[2]

with open(data_path, encoding='utf-8') as f:
    d = json.load(f)

meta     = d['Metadata']
findings = d['Findings']

# ── Color palette ─────────────────────────────────────────────────────────────
NAVY    = '0F2544'
ORANGE  = 'E8621A'
BLUE    = '3B7DD8'
WHITE   = 'FFFFFF'
LGRAY   = 'F4F7FB'
MGRAY   = 'E2E8F0'
DGRAY   = '6B7280'
RED     = 'DC2626'
AMBER   = 'CA8A04'
GREEN   = '059669'
ROSE    = 'FEF2F2'
AMBER_L = 'FFFBEB'
GREEN_L = 'F0FDF4'
NA_L    = 'F9FAFB'

SEV_COLORS = {'Critical':'DC2626','High':'EA580C','Medium':'CA8A04','Low':'65A30D','Informational':'6B7280'}
STATE_COLORS = {'Gap':ROSE,'Partial':AMBER_L,'Satisfied':GREEN_L,'NotApplicable':NA_L}
STATE_FONT   = {'Gap':'991B1B','Partial':'92400E','Satisfied':'166534','NotApplicable':'6B7280'}

def hdr(ws, row, col, val, bg=NAVY, fg=WHITE, bold=True, wrap=False, size=10):
    c = ws.cell(row=row, column=col, value=val)
    c.font = Font(name='Arial', bold=bold, color=fg, size=size)
    c.fill = PatternFill('solid', fgColor=bg)
    c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=wrap)
    return c

def cell(ws, row, col, val, bg=None, fg='111827', bold=False, wrap=True, align='left'):
    c = ws.cell(row=row, column=col, value=val)
    c.font = Font(name='Arial', color=fg, bold=bold, size=9)
    if bg: c.fill = PatternFill('solid', fgColor=bg)
    c.alignment = Alignment(horizontal=align, vertical='top', wrap_text=wrap)
    return c

def thin_border(ws, row, col):
    t = Border(
        left=Side(style='thin',color='E2E8F0'),
        right=Side(style='thin',color='E2E8F0'),
        top=Side(style='thin',color='E2E8F0'),
        bottom=Side(style='thin',color='E2E8F0')
    )
    ws.cell(row=row, column=col).border = t

wb = Workbook()

# ═══════════════════════════════════════════════════════════════════════
# SHEET 1: SUMMARY
# ═══════════════════════════════════════════════════════════════════════
ws = wb.active
ws.title = 'Summary'
ws.sheet_view.showGridLines = False
ws.column_dimensions['A'].width = 28
ws.column_dimensions['B'].width = 18
ws.column_dimensions['C'].width = 22
ws.column_dimensions['D'].width = 18

# Title banner
ws.row_dimensions[1].height = 36
ws.merge_cells('A1:D1')
t = ws['A1']
t.value = f"M365 Security Assessment — {meta['TenantDomain']}"
t.font = Font(name='Arial', bold=True, size=16, color=WHITE)
t.fill = PatternFill('solid', fgColor=NAVY)
t.alignment = Alignment(horizontal='center', vertical='center')

ws.merge_cells('A2:D2')
s = ws['A2']
s.value = f"Generated: {meta['AssessmentDate']}  |  Tool: NRG-Assessment v{meta['ToolVersion']}"
s.font = Font(name='Arial', size=9, color='6B7280')
s.alignment = Alignment(horizontal='center')

# Score section
total = len(findings)
gaps  = sum(1 for f in findings if f['State']=='Gap')
parts = sum(1 for f in findings if f['State']=='Partial')
sats  = sum(1 for f in findings if f['State']=='Satisfied')
nas   = sum(1 for f in findings if f['State']=='NotApplicable')
scored = total - nas
score  = round(100*(sats+0.5*parts)/scored) if scored else 0
posture = 'Strong' if score>=85 else 'Moderate' if score>=65 else 'At Risk' if score>=40 else 'Critical Risk'

hdr(ws,4,1,'Metric',NAVY,WHITE); hdr(ws,4,2,'Value',NAVY,WHITE); hdr(ws,4,3,'Metric',NAVY,WHITE); hdr(ws,4,4,'Value',NAVY,WHITE)
rows4 = [
    ('Security Score', f'{score}/100', 'Posture', posture),
    ('Total Controls', total,          'Gaps',    gaps),
    ('Satisfied',      sats,           'Partial', parts),
    ('Not Applicable', nas,            'Assessed',scored),
]
for i,(l1,v1,l2,v2) in enumerate(rows4,5):
    cell(ws,i,1,l1,LGRAY,NAVY,True)
    cell(ws,i,2,v1,WHITE,'111827',True,align='center')
    cell(ws,i,3,l2,LGRAY,NAVY,True)
    cell(ws,i,4,v2,WHITE,'111827',True,align='center')
    ws.row_dimensions[i].height = 18

# Severity breakdown
ws.merge_cells('A10:D10')
hdr(ws,10,1,'Gap Severity Breakdown',ORANGE,WHITE)
sev_hdr = ['Critical','High','Medium','Low']
for j,s2 in enumerate(sev_hdr,1):
    hdr(ws,11,j,s2,SEV_COLORS[s2],WHITE,size=9)
    cnt = sum(1 for f in findings if f['State']=='Gap' and f['Severity']==s2)
    cell(ws,12,j,cnt,WHITE,SEV_COLORS[s2],True,align='center')

# Workload scores
ws.merge_cells('A14:D14')
hdr(ws,14,1,'Score by Workload',BLUE,WHITE)
hdr(ws,15,1,'Workload',MGRAY,NAVY); hdr(ws,15,2,'Score',MGRAY,NAVY); hdr(ws,15,3,'Gaps',MGRAY,NAVY); hdr(ws,15,4,'Controls',MGRAY,NAVY)
wl_names={'AAD':'Identity & Access','EXO':'Exchange Online','DNS':'DNS Email Auth','DEF':'Microsoft Defender',
          'SPO':'SharePoint/OneDrive','TMS':'Microsoft Teams','INT':'Intune/Endpoint','PVW':'Purview/Compliance','PPL':'Power Platform'}
from collections import defaultdict
wl_groups = defaultdict(list)
for f in findings:
    wl = f['ControlId'].split('-')[0]
    wl_groups[wl].append(f)
row=16
for wl in ['AAD','EXO','DEF','DNS','SPO','TMS','INT','PVW','PPL']:
    grp = wl_groups.get(wl,[])
    if not grp: continue
    wn  = sum(1 for f in grp if f['State']!='NotApplicable')
    ws2 = sum(1 for f in grp if f['State']=='Satisfied')
    wp2 = sum(1 for f in grp if f['State']=='Partial')
    wg2 = sum(1 for f in grp if f['State']=='Gap')
    wsc = round(100*(ws2+0.5*wp2)/wn) if wn else 0
    col2= GREEN if wsc>=85 else AMBER if wsc>=65 else 'EA580C' if wsc>=40 else RED
    cell(ws,row,1,wl_names.get(wl,wl),LGRAY,NAVY)
    cell(ws,row,2,f'{wsc}/100',WHITE,col2,True,align='center')
    cell(ws,row,3,wg2,WHITE,RED if wg2>0 else GREEN,True,align='center')
    cell(ws,row,4,len(grp),WHITE,'111827',align='center')
    ws.row_dimensions[row].height = 16
    row+=1

# Framework scores
fws = {'CIS':'CIS M365 v6.0.1','SCuBA':'CISA SCuBA','NIST':'NIST 800-53r5','CMMC':'CMMC 2.0 L2',
       'ISO27001':'ISO 27001:2022','SOC2':'SOC 2','HIPAA':'HIPAA §164','PCIDSS':'PCI DSS v4.0'}
ws.merge_cells(f'A{row+1}:D{row+1}')
hdr(ws,row+1,1,'Framework Compliance',NAVY,WHITE)
hdr(ws,row+2,1,'Framework',MGRAY,NAVY); hdr(ws,row+2,2,'Score',MGRAY,NAVY)
hdr(ws,row+2,3,'Mapped Controls',MGRAY,NAVY); hdr(ws,row+2,4,'Reference',MGRAY,NAVY)
row+=3
for fw, fname in fws.items():
    ff = [f for f in findings if any(fw in fid for fid in f['FrameworkIds'])]
    fd = [f for f in ff if f['State']!='NotApplicable']
    fs = sum(1 for f in fd if f['State']=='Satisfied')
    fp = sum(1 for f in fd if f['State']=='Partial')
    fsc= round(100*(fs+0.5*fp)/len(fd)) if fd else 0
    fcol=GREEN if fsc>=85 else AMBER if fsc>=65 else 'EA580C' if fsc>=40 else RED
    cell(ws,row,1,fname,LGRAY,NAVY); cell(ws,row,2,f'{fsc}%',WHITE,fcol,True,align='center')
    cell(ws,row,3,len(fd),WHITE,'111827',align='center'); cell(ws,row,4,fw,WHITE,DGRAY)
    ws.row_dimensions[row].height=16; row+=1

# ═══════════════════════════════════════════════════════════════════════
def build_findings_sheet(wb, title, rows, columns):
    ws2 = wb.create_sheet(title)
    ws2.sheet_view.showGridLines = False
    ws2.freeze_panes = 'A3'
    # Banner
    ws2.merge_cells(f'A1:{get_column_letter(len(columns))}1')
    t2 = ws2['A1']
    t2.value = f'{title} — {meta["TenantDomain"]}'
    t2.font = Font(name='Arial', bold=True, size=11, color=WHITE)
    t2.fill = PatternFill('solid', fgColor=NAVY)
    t2.alignment = Alignment(horizontal='center', vertical='center')
    ws2.row_dimensions[1].height = 26
    # Headers
    for j,(col_name,width) in enumerate(columns,1):
        hdr(ws2, 2, j, col_name, ORANGE, WHITE, size=9)
        ws2.column_dimensions[get_column_letter(j)].width = width
    ws2.row_dimensions[2].height = 18
    # Data
    for i,row2 in enumerate(rows,3):
        bg = STATE_COLORS.get(row2.get('State',''),'')
        fg_state = STATE_FONT.get(row2.get('State',''),'111827')
        ws2.row_dimensions[i].height = max(15, min(60, 10 + len(str(row2.get('Detail','')))/8))
        for j,(col_name,_) in enumerate(columns,1):
            key = col_name.replace(' ','').replace('/','')
            val = row2.get(col_name, row2.get(key, ''))
            fg2 = fg_state if col_name == 'State' else ('111827' if col_name not in ('Severity',) else SEV_COLORS.get(str(val),'111827'))
            c2 = cell(ws2, i, j, val, bg, fg2, bold=(col_name=='State'))
            thin_border(ws2, i, j)
    # Auto-filter
    ws2.auto_filter.ref = f'A2:{get_column_letter(len(columns))}{len(rows)+2}'
    return ws2

ALL_COLS = [
    ('Control ID',18),('Title',36),('Category',14),('State',12),
    ('Severity',10),('Current Value',22),('Required Value',22),
    ('Business Risk',36),('Remediation',40),('CIS',12),('SCuBA',16),
    ('NIST',14),('CMMC',14),('ISO 27001',14),('SOC 2',14),('HIPAA',14),
    ('License',28),('MITRE',20),
]

def map_row(f):
    return {
        'Control ID': f['ControlId'], 'Title': f['Title'], 'Category': f['Category'],
        'State': f['State'], 'Severity': f['Severity'],
        'Current Value': f['CurrentValue'], 'Required Value': f['RequiredValue'],
        'Business Risk': f['BusinessRisk'], 'Remediation': f['Remediation'],
        'CIS': f['CIS'], 'SCuBA': f['SCuBA'], 'NIST': f['NIST'], 'CMMC': f['CMMC'],
        'ISO 27001': f.get('ISO27001',''), 'SOC 2': f.get('SOC2',''),
        'HIPAA': f.get('HIPAA',''), 'License': f['LicenseReq'], 'MITRE': f['MITRE'],
        'Detail': f['Detail'],
    }

all_rows  = [map_row(f) for f in sorted(findings, key=lambda x:(
    ['Gap','Partial','Satisfied','NotApplicable'].index(x['State']) if x['State'] in
    ['Gap','Partial','Satisfied','NotApplicable'] else 9, x['ControlId']))]
gap_rows  = [r for r in all_rows if r['State'] in ('Gap','Partial')]

# Sheet 2: All Controls
build_findings_sheet(wb, 'All Controls', all_rows, ALL_COLS)

# Sheet 3: Gaps Only
build_findings_sheet(wb, 'Gaps & Partials', gap_rows, ALL_COLS)

# Framework-specific sheets
FW_SHEETS = [
    ('CIS M365 v6', 'CIS',      'CIS',       [('Control ID',16),('Title',36),('State',12),('Severity',10),('CIS Ref',14),('Remediation',40)]),
    ('CISA SCuBA',  'SCuBA',    'SCuBA',      [('Control ID',16),('Title',36),('State',12),('Severity',10),('SCuBA Ref',18),('Remediation',40)]),
    ('NIST 800-53', 'NIST',     'NIST',       [('Control ID',16),('Title',36),('State',12),('Severity',10),('NIST Ref',14),('Business Risk',40)]),
    ('CMMC 2.0',    'CMMC',     'CMMC',       [('Control ID',16),('Title',36),('State',12),('Severity',10),('CMMC Ref',14),('Remediation',40)]),
    ('ISO 27001',   'ISO27001', 'ISO 27001',  [('Control ID',16),('Title',36),('State',12),('Severity',10),('ISO Ref',14),('Remediation',40)]),
    ('SOC 2',       'SOC2',     'SOC 2',      [('Control ID',16),('Title',36),('State',12),('Severity',10),('SOC2 Ref',14),('Remediation',40)]),
    ('HIPAA §164',  'HIPAA',    'HIPAA',      [('Control ID',16),('Title',36),('State',12),('Severity',10),('HIPAA Ref',14),('Remediation',40)]),
]
for sheet_title, fw_key, ref_col_name, cols in FW_SHEETS:
    fw_rows = []
    for f in findings:
        ref = f.get(fw_key,'') or (f.get('ISO27001','') if fw_key=='ISO27001' else '') or \
              (f.get('SOC2','') if fw_key=='SOC2' else '') or \
              (f.get('HIPAA','') if fw_key=='HIPAA' else '')
        if not ref: continue
        fw_rows.append({
            'Control ID': f['ControlId'], 'Title': f['Title'],
            'State': f['State'], 'Severity': f['Severity'],
            f'{ref_col_name} Ref': ref, 'Remediation': f['Remediation'],
            'Business Risk': f['BusinessRisk'], 'Detail': f['Detail'],
        })
    fw_rows.sort(key=lambda x:['Gap','Partial','Satisfied','NotApplicable'].index(x['State'])
                 if x['State'] in ['Gap','Partial','Satisfied','NotApplicable'] else 9)
    if fw_rows:
        build_findings_sheet(wb, sheet_title, fw_rows, cols)

# License gaps sheet
lic_rows = [map_row(f) for f in findings if f['State']=='Gap' and 'Included' not in f['LicenseReq']]
if lic_rows:
    build_findings_sheet(wb, 'License Gaps', lic_rows,
        [('Control ID',16),('Title',36),('State',12),('Severity',10),('License',32),('Remediation',40)])

wb.save(out_path)
print(f"XLSX saved: {out_path}")
'@

        # Audit fix (v4.6.x MED #4): py helper also co-located with the XLSX
        # output. The Python source itself isn't tenant-sensitive, but keeping
        # all generation artifacts in one ACL-hardened directory simplifies
        # cleanup and removes the TEMP-race surface entirely.
        $pyTmp = Join-Path $outputDir "$matrixBase-matrix-helper.py"
        try {
            $pyScript | Out-File -LiteralPath $pyTmp -Encoding utf8
            $result = & $pythonCmd $pyTmp $tmpJson $OutputPath 2>&1
            if ($LASTEXITCODE -ne 0) {
                Write-Warning "XLSX generation failed: $result"
            } else {
                Write-Verbose "XLSX: $result"
            }
        } finally {
            Remove-Item -LiteralPath $pyTmp -ErrorAction SilentlyContinue
        }
    } finally {
        Remove-Item -LiteralPath $tmpJson -ErrorAction SilentlyContinue
    }
}
